### ISSUE TITLE
Best way to deal with arrays and `defaultValues` type

### ISSUE THREAD

**Issue by lucascurti** [airjp73/remix-validated-form#1]
I have a form to create a `program` that has an array of `programDays` and in the form a user can add or delete any amount of `programDays`.

![image](https://user-images.githubusercontent.com/2811287/145433155-5c7ecaae-d77f-4679-986f-c66ed5faec76.png)

The way I'm dealing with this array in the form is by using the following:

```jsx
  {daysIds.map((id, index) => (
    <FormStack width="full" key={id.id}>
      <FormSelect
        name={`programDays.${index}.day`}
        label="Día"
        isRequired
        placeholder="Seleccionar día"
      >
        <option value={Weekdays.MONDAY}>Lunes</option>
        <option value={Weekdays.TUESDAY}>Martes</option>
        <option value={Weekdays.WEDNESDAY}>Miércoles</option>
        <option value={Weekdays.THURSDAY}>Jueves</option>
        <option value={Weekdays.FRIDAY}>Viernes</option>
        <option value={Weekdays.SATURDAY}>Sábado</option>
        <option value={Weekdays.SUNDAY}>Doming</option>
      </FormSelect>
      <FormInput
        name={`programDays.${index}.fromTime`}
        label="Hora Inicio"
        type="time"
        isRequired
        step="1800"
      />
      <FormInput
        name={`programDays.${index}.toTime`}
        label="Hora Fin"
        type="time"
        isRequired
        step="1800" // 30 min
      />
    </FormStack>
```

This means that the forms ends up with fields such us `programDays.0.day` so I'm using a custom validator that unflattens the data and validate it with zod:

**zod schema sample:**
```js
const programSchema = z.object({
  ...
  programDays: z
    .object({
      day: z.nativeEnum(Weekdays, {
        errorMap: (issue) => ({
          message: "Day can't be empty",
        }),
      }),
      fromTime: z.string().nonempty("From Time can't be empty"),
      toTime: z.string().nonempty("To Time can't be empty"),
    })
    .array(),
});
```

**custom Validator:**
```js
import { FieldErrors, Validator } from "remix-validated-form";
import { z } from "zod";
import { flatten, unflatten } from "flat";

const isObject = (obj: unknown) => {
  return Object.prototype.toString.call(obj) === "[object Object]";
};

function unFlattenData(data: unknown): unknown {
  if (!isObject(data)) return data;

  return unflatten(data);
}

export function flattenData(data: unknown): unknown {
  if (!isObject(data)) return data;

  return flatten(data);
}

export function withZodFlatten<T>(zodSchema: z.Schema<T>): Validator<T> {
  return {
    validate: (value: unknown) => {
      const result = zodSchema.safeParse(unFlattenData(value));
      if (result.success) return { data: result.data, error: undefined };

      const fieldErrors: FieldErrors = {};
      getIssuesForError(result.error).forEach((issue) => {
        const path = issue.path.join(".");
        if (!fieldErrors[path]) fieldErrors[path] = issue.message;
      });
      return { error: fieldErrors, data: undefined };
    },
    validateField: (data, field) => {
      const result = zodSchema.safeParse(unFlattenData(data));
      if (result.success) return { error: undefined };
      return {
        error: getIssuesForError(result.error).find(
          (issue) => issue.path.join(".") === field
        )?.message,
      };
    },
  };
}
```

When using `defaultValues` I have to flatten the data so the array is converted to something like `programDays.0.day: "MONDAY"` so it can be used as the Form field names. 

```jsx
  const programFormValidator = withZodFlatten(programSchema);
  ...
  <ValidatedForm
    validator={programFormValidator}
    defaultValues={flattenData(defaultValues)}
    method="post"
  >
```

The form is working and all validation errors are been shown as expected but my only issue is with `defaultValues` type. The type for it is `Partial<DataType>;` that is taken from the `validator`. In this case, it's a `zod` schema that has an array of `programDays` objects but I'm passing the flatten version of it where it's no longer an array but something like:
```js
  ...
  'programDays.0.id': 8,
  'programDays.0.day': 'MONDAY',
  'programDays.0.fromTime': '20:00',
  'programDays.0.toTime': '21:00',
```
![image](https://user-images.githubusercontent.com/2811287/145436786-5304b7bf-4347-4072-9f94-4e20dc50e08b.png)

@airjp73 I was wondering if you can think of any workaround for this. I've been trying to come up with a solution but all I can think of is using `unknown` for `defaultValues`.

**Comment by airjp73** [comment]
Thanks for the issue @lucascurti!

I'm gonna let this bounce around in my head for a couple days. For now you can get around the type issue by doing this:
```tsx
defaultValues={flattenData(defaultValues) as any}
```

One idea I'm having is to add an optional `toFieldValues` prop on `ValidatedForm`. So you would do something like this:
```tsx
defaultValues={defaultValues}
toFieldValues={flattenData}
```

I sometimes set the `defaultValues` manually so I like the utility of having the type of `defaultValues` be the validated/parsed type of the form.

Totally open to other ideas!

---

Another minor point: You don't actually need a custom validator to get the transformation you want. Zod allows you to do this:
```js
const schema = z.preprocess(
  unflattenData,
  z.object({
    foo: z.string(),
  })
);
```

**Comment by lucascurti** [comment]
I'm thinking more on a solution where the developer won't even have to worry about flattening or unflattening the data or schema. What do you think about doing something like this:
-  Add a `hasDeepData` flag to `<ValidatedForm>` and add it to the context.
- Then in the `useField` hook, if `hasDeepData === true` and `name` has a period in it, split the name (`name.split(".")`) and do some logic to get the default value from `defaultValues` instead of `defaultValues?.[name]`
- For the Validator you can also add a flag to check if data should be unflatten or it can be unflatten by default because `unflattenData` will be the same as `data` when there are no nested objects or arrays. Only edge case is if someone uses a period in a field name and they don't want it to be treated as an array or child object. Another option would be to add a new validator to the library: `withZodDeepData()`

Not sure about the `hasDeepData` name. The idea is to use something that makes it clear that the schema has child objects and/or arrays.

I think this approach would improve the developer experience and will make it easier to create forms with nested fields. It should be clear in the Readme that always a period should be used for the names in the form. I've seen that some languages such as php uses `name="persons[0][name]"`

**Comment by lucascurti** [comment]
I had a discussion about this with @airjp73 over Discord and agreed that the best way to go is to accept arrays and nested objects by default since it's a common need. I'll be working on a PR.

As @airjp73 suggested, we will take a Formik similar approach:  https://formik.org/docs/guides/arrays

@airjp73 it's ok if we use https://www.npmjs.com/package/flat or do you think a custom solution would be better?

**Comment by airjp73** [comment]
I'm okay with using `flat`, it's a small package with no dependencies so I'm not worried about bundle size.

---

So overall, I think our requirements look a bit like this:

* Support dot and bracket notation for nested objects and arrays (`field.nested[0].value`)
* Accept un-nested data in the `defaultValues` prop and give it to the correct fields
```js
<ValidatedForm
  defaultValues={{ field: { nested: [{ value: 'someValue' }] } }}
  // ...etc
/>

useField('field.nested[0].value') // <- returns 'someValue' as the defaultValue
```
* Support nested fields when validating somehow

I want to make sure to hash out this last point some. I'm thinking that the `Validator` object can handle unflattening the object itself, but we could provide a util to make that easier for people who want to make their own validators. Something like this:

```js
export function withZod<T>(zodSchema: z.Schema<T>): Validator<T> {
  return createValidator<T>({
    // everything inside here remains the same
    // createValidator handles unflattening the data and passes that data to the validator
  })
}
```

Does that seem reasonable @lucascurti?

## Optional

* Fields that contain dots or brackets and are not nested or turning off nesting completely

I don't think this is going to be common enough to be a huge issue if we don't support it. We can always add support later. If you feel like doing this, I think taking a page from Formik's book and doing the `[not.nested]` notation works for me, too.

**Comment by lucascurti** [comment]
@airjp73 I agree with those approaches. I'll let you know as soon as I have something working. Probably next week since I'm traveling tomorrow.
