### ISSUE TITLE
[Bug]: one valued array is flattened

### ISSUE THREAD

**Issue by arpitdalal** [airjp73/remix-validated-form#102]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form`: ^4.3.0
- `@remix-validated-form/with-yup`: ^2.0.1

### Please provide a link to a minimal reproduction of the issue.

https://stackblitz.com/github/arpitdalal/rmx-validated-form-checkbox

### Steps to Reproduce the Bug or Issue

Steps are in the stackblitz

### Expected behavior

I didn't expect the one valued array to be flattened to a string. The problem I believe is in [objectFromPathEntries](https://github.com/airjp73/remix-validated-form/blob/main/packages/remix-validated-form/src/internal/flatten.ts#L4). It is flattening the one valued array. I haven't been able to resolve it, so posting this here. If you have more idea about why this happens, please do comment.

### Platform

- OS: Ubuntu 20.04
- Browser: Chrome, Firefox
- Version: *

### Additional context

This only happens when there is only 1 value in the array but not when there are multiple values.

**Comment by airjp73** [comment]
Unfortunately, this is a limitation we have to live with. If there's only one value in the FormData, there's really no way for us to tell whether or not it's supposed to be an array. So one value is always a single value, and multiple values is always an array. This is documented [here](https://www.remix-validated-form.io/repeated-field-names).

One solution for this is via [`repeatable` from `zod-form-data`](https://www.remix-validated-form.io/zod-form-data/api-reference#repeatable). We don't currently any built-in helpers for handling this with yup, though it's probably not too hard to write one.

**Comment by arpitdalal** [comment]
hmm... I think this can be solved.
I found the problem, it is with this part in [here](https://github.com/airjp73/remix-validated-form/blob/main/packages/remix-validated-form/src/internal/flatten.ts#L8)
```ts
(acc, [key, value]) => set(acc, key, value.length === 1 ? value[0] : value),
```
If I change this to
```ts
(acc, [key, value]) => set(acc, key, value),
```
it fixes the problem.
Is there a specific reason, you are checking if the value only has 1 length or not?

**Comment by arpitdalal** [comment]
Yes, you're right, I tried that with a normal `input:text` and got `[ "text" ]` back with an error. There's no internal solution to this? Isn't there a way to know if this key should be an array or not?

**Comment by airjp73** [comment]
Unfortunately no -- not to my knowledge. The only way to know the developer's intent is through the validation schema, which is why `zfd.repeatable` exists.

**Comment by arpitdalal** [comment]
I'm a little confused, does `withYup.validate` call `createValidator.validate`?

**Comment by arpitdalal** [comment]
I'm trying to utilize the `yup.array()` to know if a key is defined as an array by the developer

**Comment by arpitdalal** [comment]
@airjp73 How can I utilize methods like [ensure](https://www.npmjs.com/package/yup#arrayensure-schema) with yup? That method ensures sending an array but `validator.validate` still returns a string and I get that why but I am lost here, I might have to just stick with using checkboxes with `formData.getAll`

**Comment by airjp73** [comment]
Hmm, yeah it doesn't seem like yup actually makes it easy to do this kind of preprocessing.

The closest I got was this:
```ts
const repeatableOfType = <T extends yup.AnySchema>(schema: T) =>
  yup.lazy((val) => {
    if (Array.isArray(val)) return yup.array(schema);
    return schema.transform((val) => [val]);
  });

const validator = withYup(
  yup.object({
    checkboxes: repeatableOfType(yup.string())
  })
);
```

But that's still not perfect. The types aren't quite right and if there are no values it results in an `undefined`.

**Comment by arpitdalal** [comment]
I was trying to add a method to the `yup.array` schema with their `addMehtod` method: https://www.npmjs.com/package/yup#yupaddmethodschematype-schema-name-string-method--schema-void
