### ISSUE TITLE
[Feature]: getValues for useFormContext

### ISSUE THREAD

**Issue by xEnigma** [airjp73/remix-validated-form#115]
### What is the new or updated feature that you are suggesting?

It would be great if the `useFormContext` hook exposes a method like `getValues` ([see example from RHF](https://react-hook-form.com/api/useform/getvalues/)) that keeps track of the form values.

### Why should this feature be included?

This is useful especially for building more complex input components. Think of a DatePicker that synchronizes between a plain text input field and a visual date picker component.

Another use case I have: I want to display the values in another component additionally to the inputs. So it would be great to be able to read these values and show them.

**Comment by airjp73** [comment]
Hi!

This is something I've iterated on quite a bit. One of the things I like about remix is that we don't need to track the form values in state. As a result we don't actually have some easy state to extract values from. This could probably be clarified a bit by the docs.

However, there's a [useControlField](https://www.remix-validated-form.io/reference/use-control-field) hook that should work well for the two use cases you described.

**Comment by airjp73** [comment]
I'm going to close this because I think `useControlField` should cover it. It's also possible to get the `FormData` directly by passing a `formRef` to the `ValidatedForm` if you need to grab the raw data imperatively.
