### ISSUE TITLE
[Bug]: Scroll to top on route change doesn't work

### ISSUE THREAD

**Issue by mabramian** [airjp73/remix-validated-form#126]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- "remix-validated-form": "4.5.0"
- "@remix-validated-form/with-zod": "2.0.1"

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/s/snowy-leftpad-391gzf

### Steps to Reproduce the Bug or Issue

1. Go to codesandbox
2. Scroll to the bottom
3. Click **Submit** button

Trying to have the browser scroll to the top upon moving to next page using `redirect`. It is preserving the scroll position.
I added `ScrollRestoration` to the root.
Using **1.2.3** remix version.

### Expected behavior

As a user, I expected scrolling to the top after redirect like remix `Link `doing it but I am seeing preserving the scroll position

### Platform

- OS: Windows
- Browser:  Chrome
- Version:  102.0.5005.63

**Comment by airjp73** [comment]
Hi! It looks like this is more of a remix issue than a remix-validated-form issue. Could you file an issue over there?

Here's a fork of that sandbox that reproduces the issue without using remix-validated-form: https://codesandbox.io/s/spring-frog-eczkn1?file=/app/routes/index.tsx

**Comment by mabramian** [comment]
Hi!
You're right
Pull request in Remix repo for fixing it - https://github.com/remix-run/remix/pull/3171
