### ISSUE TITLE
[Feature]: Support Remix 1.6.5 `useActionData/useLoaderData` type inference

### ISSUE THREAD

**Issue by chungweileong94** [airjp73/remix-validated-form#140]
### What is the new or updated feature that you are suggesting?

With the new Remix 1.6.5, both `useActionData` & `useLoaderData` will now able to infer the response type. However, due to the fact that `remix-validated-form` still relies on the type from remix v1.2.X, remix type inference will not able to work properly.

For example:
```tsx
import {ValidatedForm, validationError} from 'remix-validated-form';
import {withZod} from '@remix-validated-form/with-zod';

const formValidator = withZod(/** ... */);

export const action = async ({request}: ActionArgs) => {
  const formData = await request.formData();
  const data = await formValidator.validate(formData);
  if (data.error) return validationError(data.error);
  return json('Some data...');
};

const Index = () => {
  const actionData = useActionData<typeof action>();
  //    ^ This will always return `any` type
  return <ValidatedForm ...>...</ValidatedForm>
}
```

Reference: https://github.com/remix-run/remix/pull/3276

### Why should this feature be included?

As people who use this `remix-validated-form` as their form validation management library will not be able to get the latest type-support from Remix. Else the only workaround is to patch the typing in the package manually.

**Comment by chungweileong94** [comment]
As of now, I'm using `patch-package` to patch the typing manually.

```diff
diff --git a/node_modules/remix-validated-form/dist/types/server.d.ts b/node_modules/remix-validated-form/dist/types/server.d.ts
index 69f833e..55f3029 100644
--- a/node_modules/remix-validated-form/dist/types/server.d.ts
+++ b/node_modules/remix-validated-form/dist/types/server.d.ts
@@ -1,5 +1,6 @@
+import {TypedResponse} from '@remix-run/server-runtime';
 import { FORM_DEFAULTS_FIELD } from "./internal/constants";
-import { ValidatorError } from "./validation/types";
+import { ValidationErrorResponseData, ValidatorError } from "./validation/types";
 /**
  * Takes the errors from a `Validator` and returns a `Response`.
  * When you return this from your action, `ValidatedForm` on the frontend will automatically
@@ -14,7 +15,7 @@ import { ValidatorError } from "./validation/types";
  * if (result.error) return validationError(result.error, result.submittedData);
  * ```
  */
-export declare function validationError(error: ValidatorError, repopulateFields?: unknown, init?: ResponseInit): Response;
+export declare function validationError(error: ValidatorError, repopulateFields?: unknown, init?: ResponseInit): TypedResponse<ValidationErrorResponseData>;
 export declare type FormDefaults = {
     [formDefaultsKey: `${typeof FORM_DEFAULTS_FIELD}_${string}`]: any;
 };
```

**Comment by airjp73** [comment]
Hi! Good callout. That fix looks pretty straightforward & reasonable. Would you mind opening a PR for it?

**Comment by airjp73** [comment]
Published in 4.5.2

**Comment by chungweileong94** [comment]
> Published in 4.5.2

@airjp73 This version doesn't seem to include the latest change, am I missing anything in PR #142?

**Comment by airjp73** [comment]
It's possible I messed something up. I'll check after work tonight.

**Comment by airjp73** [comment]
_Now_ it should be working (v4.5.3). Importing `json` from `@remix-run/server-runtime` didn't seem to work, but importing straight from `remix` appears to. Could you give it a try?

**Comment by chungweileong94** [comment]
> _Now_ it should be working (v4.5.3). Importing `json` from `@remix-run/server-runtime` didn't seem to work, but importing straight from `remix` appears to. Could you give it a try?

Just tested, and all good. Thanks!

**Comment by yarapolana** [comment]
Can't seem to make this work. @chungweileong94 can you share what you did?

**Comment by chungweileong94** [comment]
> Can't seem to make this work, using 4.6.8. @chungweileong94 can you share what you did?
> 
> ```
> export const action = async ({request}: ActionArgs) => {
>   const formData = await request.formData();
>   const data = await formValidator.validate(formData);
>   if (data.error) return validationError(data.error);
>   return json('Some data...');
> };
> 
> ...
> const Index = () => {
>   const actionData = useActionData<typeof action>();
>   //    actionData.somedata <-- this is not being recognized
>   return ...
> }
> ...
> ```
> 
> Should this be happening instead?
> 
> ```
> export const action = async ({request}: ActionArgs) => {
>   ...
>   if (data.error) return json({somedata: null, ...validationError(data.error)});
>   return json('Some data...');
> };
> ```

First of all, the `actionData` should be a string based on your code snippet, that's why `actionData.someData` is not valid. Secondly, Your `action` return both `validationError` & `json('...')`, which means you will have to use type guard to get the type works.

You can refer to this [example](https://github.com/chungweileong94/social-linker/blob/main/app/routes/index.tsx), it might be slightly complex to you, but it covers all the things you need.

**Comment by yarapolana** [comment]
> > Can't seem to make this work, using 4.6.8. @chungweileong94 can you share what you did?
> 
> > 
> 
> > ```
> 
> > export const action = async ({request}: ActionArgs) => {
> 
> >   const formData = await request.formData();
> 
> >   const data = await formValidator.validate(formData);
> 
> >   if (data.error) return validationError(data.error);
> 
> >   return json('Some data...');
> 
> > };
> 
> > 
> 
> > ...
> 
> > const Index = () => {
> 
> >   const actionData = useActionData<typeof action>();
> 
> >   //    actionData.somedata <-- this is not being recognized
> 
> >   return ...
> 
> > }
> 
> > ...
> 
> > ```
> 
> > 
> 
> > Should this be happening instead?
> 
> > 
> 
> > ```
> 
> > export const action = async ({request}: ActionArgs) => {
> 
> >   ...
> 
> >   if (data.error) return json({somedata: null, ...validationError(data.error)});
> 
> >   return json('Some data...');
> 
> > };
> 
> > ```
> 
> 
> 
> First of all, the `actionData` should be a string based on your code snippet, that's why `actionData.someData` is not valid. Secondly, Your `action` return both `validationError` & `json('...')`, which means you will have to use type guard in order to get the type works.
> 
> 
> 
> You can refer to this [example](https://github.com/chungweileong94/social-linker/blob/main/app/routes/index.tsx), it might be slightly complex, but it covers all the things you need.
> 
> 

Hey thanks for replying, not complex at all. Number 1 is an example, the some data string return is not from "real code" thought that would be clear.

In the example you gave, you are not inferring the _typeof action_ you declare a type to pass on your json, though that might work for your case, that goes out of the reason for having the inferring from _typeof action_ working without having to declare more types along the way.

**Comment by chungweileong94** [comment]
> > > Can't seem to make this work, using 4.6.8. @chungweileong94 can you share what you did?
> > 
> > > 
> > 
> > > ```
> > 
> > > export const action = async ({request}: ActionArgs) => {
> > 
> > >   const formData = await request.formData();
> > 
> > >   const data = await formValidator.validate(formData);
> > 
> > >   if (data.error) return validationError(data.error);
> > 
> > >   return json('Some data...');
> > 
> > > };
> > 
> > > 
> > 
> > > ...
> > 
> > > const Index = () => {
> > 
> > >   const actionData = useActionData<typeof action>();
> > 
> > >   //    actionData.somedata <-- this is not being recognized
> > 
> > >   return ...
> > 
> > > }
> > 
> > > ...
> > 
> > > ```
> > 
> > > 
> > 
> > > Should this be happening instead?
> > 
> > > 
> > 
> > > ```
> > 
> > > export const action = async ({request}: ActionArgs) => {
> > 
> > >   ...
> > 
> > >   if (data.error) return json({somedata: null, ...validationError(data.error)});
> > 
> > >   return json('Some data...');
> > 
> > > };
> > 
> > > ```
> > 
> > 
> > 
> > First of all, the `actionData` should be a string based on your code snippet, that's why `actionData.someData` is not valid. Secondly, Your `action` return both `validationError` & `json('...')`, which means you will have to use type guard in order to get the type works.
> > 
> > 
> > 
> > You can refer to this [example](https://github.com/chungweileong94/social-linker/blob/main/app/routes/index.tsx), it might be slightly complex, but it covers all the things you need.
> > 
> > 
> 
> Hey thanks for replying, not complex at all. Number 1 is an example, the some data string return is not from "real code" thought that would be clear.
> 
> In the example you gave, you are not inferring the _typeof action_ you declare a type to pass on your json, though that might work for your case, that goes out of the reason for having the inferring from _typeof action_ working without having to declare more types along the way.

I pretty sure the generic type is optional, it's just a habit of mine at the time. Without the generic if should I get the type as usual.

**Comment by yarapolana** [comment]
That is where my initial problem lies. Let me go back to the beginning.

![image](https://user-images.githubusercontent.com/19730118/218515241-e6afeba5-8c8e-4675-90e6-92a78b36ebaa.png)

actionData.data / error don't get inferred well, I have to do this 

![image](https://user-images.githubusercontent.com/19730118/218515854-de7e236f-d85e-429c-adbb-d54d4c56c640.png)

To get the data and error recognized. My question is, is there anything I am missing to be able to infer `data` and `error` when `validationError` is involved?

**Comment by chungweileong94** [comment]
@yarapolana I understand your problem, and I don't there's much we can do to get the type to infer the way we wanted to without type-guard.

And doing `json({data: null, error: null, ...validationError(...)})` will fix the type infer, but it will break `remix-validated-form`, in terms of client-side error prompting (haven't really tested, but I believe it will). Because both `json(...)` & `validationError(...)` return a [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response/Response) object, that's why spreading the `validationError` will eventually break things, that's also why the type-infer doesn't work in the first place, as the return type of the `action` will become something like `Response<...> | Response<...>`

**Comment by yarapolana** [comment]
Spreading the validation works, tested it when I first mentioned it. Honestly just wanted to open the conversation up. 

I mentioned with someone from remix on twitter about how inferring types when having multiple types of returns doesn't work, and they said were looking into it, but you never know when an official version/tutorial/tip might come out.

Thanks for the chat @chungweileong94 . Have a good one.

**Comment by alexbu92** [comment]
spreading doesn't work for me, I only get a "size" property in the returned action data..
