### ISSUE TITLE
[Bug]: different behaviour with error messages between schema in zod-form-data and zod schema, when used in validator

### ISSUE THREAD

**Issue by abenhamdine** [airjp73/remix-validated-form#145]
### Which packages are impacted?

- [ ] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [X] `zod-form-data`

### What version of these packages are you using?

    "@remix-run/express": "^1.6.5",
    "@remix-run/node": "^1.6.5",
    "@remix-run/react": "^1.6.5",
    "@remix-validated-form/with-zod": "^2.0.1",
    "remix-validated-form": "^4.5.1",
    "zod-form-data": "^1.2.1"

### Please provide a link to a minimal reproduction of the issue.

not provided, but sample code is enough

### Steps to Reproduce the Bug or Issue

I try to use zod schema both for parsing and for form validator, to avoid to declare twice the same schema.
It seems to work, excepting that the error messages behaviour is different when I pass zod schema to validator

In a loader set a schema with zfd and with zod and see the differences when fields are submitted empty

```ts
const schemaWithZod = z.object({
    name: z.string().min(2, { message: "First name is required" }),
})
export const validator = withZod(schemaWithZod)
const formData = await request.formData()
const data = await validator.validate(formData)
if (data.error) return validationError(data.error)

```

![image](https://user-images.githubusercontent.com/7466144/180160309-a1652c05-88c6-4608-a241-966306c6803c.png)

```ts
const schemaWithZfd = zfd.formData({
    name: zfd.text(z.string().min(2, { message: "First name is required"})),
})
export const validator = withZod(schemaWithZfd)
const formData = await request.formData()
const data = await validator.validate(formData)
if (data.error) return validationError(data.error)
```

![image](https://user-images.githubusercontent.com/7466144/180160444-02f276aa-0edd-4b2b-a09d-de6bb1164318.png)

Notice the differences between the 2 erro messages

**However, with a wrong input of one character (less than required length of 2), the behaviour is the same with both schemas:** 

![image](https://user-images.githubusercontent.com/7466144/180161862-481790c8-3db2-4aaa-950c-6b7d482ae62a.png)

### Expected behavior

Same behaviour when I pass a zfd schema to form validator

### Platform

Mac Os Catalina
Chrome 103.0.5060.114 (Build officiel) (x86_64)

**Comment by airjp73** [comment]
Hi!

Thanks for taking the time to file an issue.

What you're seeing here is one of the primary, intended behaviors of zfd.text.

[Doc](https://www.remix-validated-form.io/zod-form-data/api-reference#text):

```
Transforms any empty strings to undefined before validating. This makes it so empty strings will fail required checks, allowing you to use optional for optional fields instead of nonempty for required fields.
```

So to get a required error message, you need to pass a required error instead of using min.


```
z.string({ required_error: "First name is required" })
```

If you prefer using `min`, then you can use plain z.string over zfd.text.

**Comment by abenhamdine** [comment]
ok thx, I get it
