### ISSUE TITLE
[Feature]: formContext.submit() should use `useSubmit` hook internally

### ISSUE THREAD

**Issue by jnicklas** [airjp73/remix-validated-form#149]
### What is the new or updated feature that you are suggesting?

The form context exposes a method to manually submit the form, running validations in the process, via the `submit` method. However, this method calls `formElement.submit()` directly:

https://github.com/airjp73/remix-validated-form/blob/f479dbf62f2cb0d39d9e0909da245a135b0838be/packages/remix-validated-form/src/internal/state/createFormStore.ts#L202-L210

This is not ideal in remix land. We want to use the `useSubmit` from remix, so that a client side transition is preferred over a full page reload.

### Why should this feature be included?

In my opinion, it is more intuitive for submit to use a client side transition, rather than a full page reload, if possible. It feels more idiomatic.

**Comment by airjp73** [comment]
Looks like I made in incorrect assumption about the behavior here. https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit

I think we should be using `requestSubmit` instead of `submit`.

**Comment by airjp73** [comment]
Fixed in v4.5.4

**Comment by jnicklas** [comment]
Wonderful, thank you!

**Comment by jnicklas** [comment]
I just tried this out, and while it works really well in Chrome, unfortunately, the requestSubmit is experimental in Safari, and not enabled by default.

<img width="803" alt="Screenshot 2022-08-05 at 18 52 23" src="https://user-images.githubusercontent.com/134/183124552-48fbc7d6-ea5f-4f37-9bce-808994be7041.png">
 
The "official" way of doing this is using the `onSubmit` hook, seems like that'd be the best solution.

**Comment by jnicklas** [comment]
I did a workaround in my app, by using the `useSubmit` hook and doing some hackery to get a reference to the form using `useRef`:

```ts
export interface FormProps<T> extends ValidatedFormProps<T> {
  children?: ReactNode;
}

let FormSubmitContext = createContext<() => void>(() => {});

export function useFormSubmit() {
  return useContext(FormSubmitContext);
}

export function Form<T>({ children, ...props }: FormProps<T>): JSX.Element {
  // this is a workaround for there being no good way of manually submitting a validated form at the moment, see:
  // https://github.com/airjp73/remix-validated-form/issues/149
  let ref = useRef<HTMLDivElement>(null);
  let submit = useSubmit();

  let formSubmit = useCallback(() => {
    setTimeout(() => submit(ref.current ? ref.current.closest('form') : null));
  }, []);

  return (
    <ValidatedForm {...props}>
      <FormSubmitContext.Provider value={formSubmit}>
        <div ref={ref}>
          {children}
        </div>
      </FormSubmitContext.Provider>
    </ValidatedForm>
  );
}
```

This kinda sorta works, but it also reveals an issue that is relevant if we want to fix this issue in remix-validated-form itself: when using this approach, the `.isSubmitting` field on the form context is not updated. I think this is because remix-validated-form uses a fetcher internally, so we really we should be using `fetcher.submit()`, but then this doesn't cause a navigation, which doesn't seem quite correct either. In my case, I am submitting the form using GET, and so the way I understand it, the URL wouldn't change, which is wrong for my use case.

It seems like getting this right is actually surprisingly tricky.

**Comment by airjp73** [comment]
Can't you use the `formRef` prop instead of a div? https://www.remix-validated-form.io/reference/validated-form#formRef

The validated form doesn't use a ref in all cases, just when you pass one in.

The browser support issue is annoying, but I can find an alternate fix.

**Comment by airjp73** [comment]
Should now work in safari as of 4.5.5
