### ISSUE TITLE
How to get the input value or success state. 

### ISSUE THREAD

**Issue by tharyckgusmao** [airjp73/remix-validated-form#16]
Hi, I'm playing with the remix a bit and I came across this lib, which I'm finding the best...

However, in one of my tests I was in doubt and would like to know if there is a possibility or need an implementation.

I would like to get the success status for validation or the input value to manage classes in css, when success and when error (I already get it).

```
   const { success[or value], error } = useField(name);

      <input
         className={success or error}
       />
```
       
       thanks

**Comment by airjp73** [comment]
Hi! I'm glad your liking the lib so far.

Can you tell me a little more about your use-case?

I've been thinking of the validation as having two states (`valid` or `invalid`), but I guess there are technically three (`not validated`, `valid`, and `invalid`). Is that what you mean? The way it is now, if the field is valid or hasn't been validated yet, then `error` will be `undefined`.

The library also doesn't track input values at all -- all the inputs can be uncontrolled. If you want the value of the input you can use a controlled input with `useState` and everything will still function correctly.

```tsx
const [value, setValue] = useState('');
const { error } = useField(name);

<input
  className={error ? 'error' : 'success'}
  value={value}
  onChange={event => setValue(event.target.value)}
/>
```

**Comment by tharyckgusmao** [comment]
Hmmm... I understood, I imagined that not providing the input state would be an internal management of the lib ecosystem, for the component not to have internal states, but stopping to think about it makes sense, because in certain cases an input value influences other values of other inputs, being uncontrolled and possibly controlled....

I liked!!

CSS scenarios are three states, neutral, success, invalid.

I'll manage the values states at a higher level to avoid prerender, I'll follow something like this:

```
const [value, setValue] = useState('');
const { error } = useField(name);

<input
  className={`${error ? 'error' :""} ${!error && value ?'success':""} }`}
  value={value}
  onChange={event => setValue(event.target.value)}
/>
```

Thank you very much! Success! Sorry for my poor English :)
