### ISSUE TITLE
[Feature]: Auto-remove  __rvfInternalFormId field from validated data when validating.

### ISSUE THREAD

**Issue by Torkan** [airjp73/remix-validated-form#164]
### What is the new or updated feature that you are suggesting?

Currently, `__rvfInternalFormId` is an included field when validating a form that has an id defined:

```
const validator = withYup(formSchema);

export const action: ActionFunction = async ({ request, params, context }) => {
  const { data, error } = await validator.validate(await request.formData());
  // Must be manually removed.
  delete data.__rvfInternalFormId;
```

### Why should this feature be included?

The validated data returned by the validator, should not return internal fields/values.

This is a fairly common use-case when using the validated data as parameters in a graphql-request for example, which ensures there is no additional parameters than specified in the query definition.

**Comment by airjp73** [comment]
Yeah, this would be good to do. `zod` automatically removes these and I missed that `yup` doesn't. Probably should remove these fields even before passing the data to the validation library [here](https://github.com/airjp73/remix-validated-form/blob/main/packages/remix-validated-form/src/validation/createValidator.ts#L24).

**Comment by Torkan** [comment]
Although I don't have a great overview of the codebase at all, I would agree it looks like a very natural place to strip internal values 👍

**Comment by alexbu92** [comment]
any ways to tell the schema to not pass that value on if the form is valid?
