### ISSUE TITLE
[Bug]: Clicked HTML button name/value are not included on client FormData but is included on server FormData

### ISSUE THREAD

**Issue by zelid** [airjp73/remix-validated-form#170]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

  "@remix-run/express": "^1.7.0",
  "@remix-run/node": "^1.7.0",
  "@remix-run/react": "^1.7.0",
  "@remix-validated-form/with-zod": "^2.0.1",
  "aws-sdk": "^2.1212.0",
  "cloudinary": "^1.31.0",
  "compression": "^1.7.4",
  "cross-env": "^7.0.3",
  "cuid": "^2.1.8",
  "express": "^4.18.1",
  "morgan": "^1.10.0",
  "nanoid": "^4.0.0",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "remix-validated-form": "^4.6.0-beta.0",
  "tiny-invariant": "^1.2.0",
  "ts-simple-nameof": "^1.3.1",
  "zod": "^3.19.0",
  "zod-form-data": "^1.2.1"

### Please provide a link to a minimal reproduction of the issue.

Code provided in "Steps to Reproduce the Bug or Issue"

### Steps to Reproduce the Bug or Issue

```
import { ActionFunction, json } from "@remix-run/node";
import { withZod } from "@remix-validated-form/with-zod";
import {
  useFormContext,
  ValidatedForm,
  validationError,
} from "remix-validated-form";
import z from "zod";

// Available form actions within the same form:
const formActions = ["submit", "uploadPhoto"] as const;

const validator = withZod(
  z.object({
    formAction: z.enum(formActions).optional(), // <--- right now I can't remove optional() because client form data misses submitted button form input name/value
  })
);

export const action: ActionFunction = async ({ request }) => {
  const formData = await request.formData();

  const validated = await validator.validate(formData);
  if (validated.error)
    return json({
      error: validationError(validated.error),
    });

  // `formAction` HAS value on the server
  const formActionOnServer = validated.data.formAction;
  console.log("formActionOnServer: ", formActionOnServer);

  return json({
    formData,
    validated,
  });
};

export default function () {
  const myFormContext = useFormContext("myForm1");
  return (
    <>
      <h1>Different actions inside same form</h1>

      <ValidatedForm
        style={{
          marginTop: "1em",
        }}
        id="myForm1"
        validator={validator}
        method="post"
      >
        {/* 
          `formAction` has NO value on the client.
          Is it a bug?
          */}
        <button name="formAction" value="uploadImage">
          Upload Image
        </button>
        <button name="formAction" value="applyCountry">
          Apply Country
        </button>
        <button name="formAction" value="submit">
          Submit
        </button>

        <pre>{JSON.stringify(myFormContext.fieldErrors)}</pre>
      </ValidatedForm>
    </>
  );
}
```

### Expected behavior

Client form data should follow the same rules as server form data: submitted button name/value should be treated as form data.

I have a form which may have different submit actions within the same form. There are several submit buttons within the same form with name `formAction` and different values like `uploadImage`, `submitForm`, etc... (full code provided in "Steps to Reproduce the Bug or Issue" section).

I want to make `formAction` mandatory in
```
const validator = withZod(
  z.object({
    formAction: z.enum(formActions).optional(),
  })
);
```
but can't do because submitted button name/value are not treated on the client as form data and required `formAction` Zod schema field would be always empty on client and trigger validation error.
On the server  inside `ActionFunction` `formAction` is properly populated from `request` as standard HTML behavior of the clicked submit button nave/value.

I'm not sure if this mismatch of client/server form data is a bug or feature.

I'm aware of `ValidatedForm's` `subactions`, but subactions are used when there are few forms on the same page and we need to track which one is submitted. But my `formAction` is used to track which action is submitted within the same form.

### Platform

any

**Comment by airjp73** [comment]
Good callout!

We grab the submitter for the form [here](https://github.com/airjp73/remix-validated-form/blob/c6a7855af7ef1815e7aceea48e56933d698d3ffe/packages/remix-validated-form/src/ValidatedForm.tsx#L325). I think the fix would be to move that up closer to [here](https://github.com/airjp73/remix-validated-form/blob/c6a7855af7ef1815e7aceea48e56933d698d3ffe/packages/remix-validated-form/src/ValidatedForm.tsx#L306) and then do

```
// might not be 100% correct api -- didn't google it
if (submitter.name) formData.set(submitter.name, submitter.value);
```

This FormData only exists for the purposes of validating and doesn't affect what actually gets submitted.
