### ISSUE TITLE
[Feature]: Allow passing error map to `withZod`

### ISSUE THREAD

**Issue by Mattinton** [airjp73/remix-validated-form#171]
### What is the new or updated feature that you are suggesting?

Currently there is no way of setting the ErrorMap apart from globally with `z.setErrorMap`,  sometimes I want to use different error maps depending on the situation. 

When just using zod on it own you can do this by passing the options parameter to `safeParse` like this `schema.safeParse({}, { errorMap })`, this functionality could be exposed by allowing a second argument to the `withZod` function.

### Why should this feature be included?

- Custom error maps per schema validator
- Allow more zod functionality

**Comment by airjp73** [comment]
It's also possible to pass the errorMap in at the schema level. Does that cover your use-case?

```
const validator = withZod(
  z.object(
    {
      myField: z.string()
    },
    {
      errorMap: () => ({ message: "error message" })
    }
  )
);
```

I'm not sure if or how we should support this when actually calling `validator.validate` though.

**Comment by Mattinton** [comment]
Your solution was the first one I jumped to when having this problem. The issue with it, is that it only applies the Error Map to that object's errors, and not the actual `myField` property's errors. So you end up having to pass the error map to every property in the object separately.

I'm guessing `validator.validate` under the hood calls `parse` or `safeParse`, so I think what I'm looking for is a method of passing the options through to that.

**Comment by Mattinton** [comment]
I guess I should add that my specific use case is returning some more user friendly error messages to the form, currently I'm getting around it by using `z.setErrorMap` but I'm not a fan of setting that option globally tbh. Remix also warns against side effects so I'm not sure if calling that is causing any issues there either.

**Comment by airjp73** [comment]
Ah, that makes sense. I think your ideal api you described looks good to me (`withZod(z.object(...), { errorMap })`). I'll happily take a PR. :)

**Comment by Mattinton** [comment]
I'll get one done when I've got some free time this week :)
