### ISSUE TITLE
[Bug]: Form errors are not cleared on submit

### ISSUE THREAD

**Issue by jnicklas** [airjp73/remix-validated-form#172]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [X] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- @remix-validated-form/with-yup@2.0.1
- remix-validated-form@4.5.5

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/s/mystifying-bhabha-j5vnvs?file=/app/routes/index.tsx

### Steps to Reproduce the Bug or Issue

When using remix-validated-form with yup, the validator uses `validateField` to validate the value on change. This works great so long as changing the value of the field only affects the validation of the field itself, but not that of other fields. With some directives in yup, this is not the case. For example with `when`, we can construct a schema like this:

```ts
yup.object().shape({
  foo: yup.boolean(),
  bar: yup.string().when('foo', { is: true, then: (s) => s.required() }),
});
```

A schema like this behaves in a rather odd way with remix-validated-form. When changing the `foo` field, the validation on the `bar` field is not affected at all. When submitting the form, the behaviour is correct in that the schema is respeced and the form is submitted if the schema is valid. However, if the validation failed, and an error is shown, then the problem is fixed and the form is resubmitted, the form does submit as it should, but the error is still shown! Thus a form which shows an error and *looks* invalid is actually successfully submitted. Likewise the `useIsValid()` hook still returns `false` even though the form successfully submitted.

### Expected behavior

There are two possible ways of solving this:

1. changing a field could revalidate the *entire* form by using `validate` rather than `validateField`, this would clear the dependent error on change. I think this would be the best user experience, but there might be other consequences to this, and it feels like a breaking change somewhat, since the behaviour would be pretty different.
2. if the form is validated on submit and the submit fails, [the field errors are set](https://github.com/airjp73/remix-validated-form/blob/cad2f30913f07c95df785f50b3494b3d64d9ad43/packages/remix-validated-form/src/ValidatedForm.tsx#L309), but there is no change to the field errors on a *successful* validation. A simple fix to get more reasonable behaviour would be to set the field errors to empty on a successful validation.

### Screenshots or Videos

https://user-images.githubusercontent.com/134/190222835-bc4af825-eb3e-4254-99cb-93f425493e9f.mov

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by airjp73** [comment]
Thanks for bringing this up! I think clearing errors on successful submit is reasonable and shouldn't be breaking.

I'd like to address this at the `validate` level, too, but I want to think on it a bit.

**Comment by airjp73** [comment]
Since the core bug is fixed now, I'm closing this issue in favor of a new issue for further, potential behavior changes.
