### ISSUE TITLE
[Feature]: Export FormData array transformation in zfd.formData

### ISSUE THREAD

**Issue by AviDuda** [airjp73/remix-validated-form#174]
### What is the new or updated feature that you are suggesting?

Export the transformation done in `zfd.formData()` [located here](https://github.com/airjp73/remix-validated-form/blob/c6a7855af7ef1815e7aceea48e56933d698d3ffe/packages/zod-form-data/src/helpers.ts#L152-L173) and make it available for use.

### Why should this feature be included?

I need to access the object made from FormData without validation applied (I'm using only the `zod-form-data` package). This gets problematic when I have arrays in FormData as zod's parse/safeParse doesn't include the data when it's invalid.  
I would like to use the exact implementation used by the library instead of copying the code to do it manually as it's always possible that the library implementation may change in the future.

My use case:

```js
const formData = await request.formData();
try {
    const schema = zfd.formData({
        items: zfd
            .repeatable(
                z.object({
                    id: zfd.numeric(),
                    name: zfd.text(),
                })
            )
            .array(),
    });
    schema.parse(formData);
    return redirect("/");
} catch (err) {
    // I need to access formData to get e.g. count of items
}
```

Doing this manually seems to work as a workaround.

```js
export function formDataToObject(formData: FormData): Record<string, unknown | unknown[]> {
    const entries = z.array(z.tuple([z.string(), z.any()]));

    return z
        .any()
        .refine((val) => Symbol.iterator in val)
        .transform((val) => [...val])
        .refine((val): val is z.infer<typeof entries> => entries.safeParse(val).success)
        .transform((data): Record<string, unknown | unknown[]> => {
            const map: Map<string, unknown[]> = new Map();
            for (const [key, value] of data) {
                if (map.has(key)) {
                    map.get(key)?.push(value);
                } else {
                    map.set(key, [value]);
                }
            }

            return [...map.entries()].reduce((acc, [key, value]) => {
                return set(acc, key, value.length === 1 ? value[0] : value);
            }, {} as Record<string, unknown | unknown[]>);
        })
        .parse(formData);
}
```

**Comment by tiavina-mika** [comment]
Is there any news on this?
