### ISSUE TITLE
[Bug]: method option not being applied

### ISSUE THREAD

**Issue by danecando** [airjp73/remix-validated-form#180]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- "remix-validated-form": "^4.5.6"

### Please provide a link to a minimal reproduction of the issue.

https://stackblitz.com/edit/node-zqp4zm?file=package.json

### Steps to Reproduce the Bug or Issue

Pass a method like 'patch' to ValidatedForm. It will not be applied the form method will still be post

### Expected behavior

I expected to be able to change the method using the method option

### Platform

- OS: latest macos
- Browser: latest chrome

**Comment by danecando** [comment]
Thanks for the quick fix I was honestly probably going to open a PR for it this week. I might follow up with a quick fix because it feels weird to me that I can change the method but it still shows as "POST" in the markup. Not a huge deal but just feels odd. Thanks as usual for all the work on this library

**Comment by airjp73** [comment]
Showing POST in the markup is an HTML limitation and is done by Remix, not this library. GET and POST are the only supported rest verbs ([reference] (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-method). PATCH only works correctly with JS enabled.

**Comment by danecando** [comment]
TIL. Thanks for the heads up surprised I wasn't aware of this already !
