### ISSUE TITLE
[Feature]: Get isRequired from useField

### ISSUE THREAD

**Issue by alexbu92** [airjp73/remix-validated-form#183]
### What is the new or updated feature that you are suggesting?

The useField hook should tell us if the field is optional or not to be able to style the input accordingly.

### Why should this feature be included?

Currently, even though required fields are being enforced through the schema, there is no way to know which inputs are actually required other than manually setting required on the inputs which seems like a waste since we're specifying that in the schema.

**Comment by airjp73** [comment]
Hi!

Unfortunately, I don't think this is something we can do. The only way I could think this would work is to inspect the validation schema and that's something I'd like to avoid doing in this library. You might be able to make something like this in userland though if you know how to get that information from `zod` or `yup`.
