### ISSUE TITLE
[Bug]: Error with installing version 2.0.3 of @remix-validated-form/with-zod

### ISSUE THREAD

**Issue by klipstein** [airjp73/remix-validated-form#200]
### Which packages are impacted?

- [ ] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- @remix-validated-form/with-zod@2.0.3

### Please provide a link to a minimal reproduction of the issue.

none

### Steps to Reproduce the Bug or Issue

Just do `npm install @remix-validated-form/with-zod@2.0.3`. Then the following error occurs:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/setGet - Not found
npm ERR! 404
npm ERR! 404  'setGet@*' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Expected behavior

It should not error with installing the wrong dependency `setGet`.

### Platform

- OS: macOS
- Browser: not relevant

**Comment by airjp73** [comment]
Ah yeah, looks like I messed up with naming one of the internal packages. It's taking longer than a few minutes to fix so I won't have time to fix it today. The previous version of the package shouldn't have the same problem.

If anyone has time to look into this today, I would take a PR.

**Comment by airjp73** [comment]
I've republished the previous patch version, so hopefully that should get things working for now.

**Comment by huaiyukhaw** [comment]
It seems working now. However package name is recommended to be all lowercase, should "setGet" be "set-get" instead?

**Comment by airjp73** [comment]
Yeah, that should be the fix. For some reason changing that didn't immediately fix things when I published a beta and tried to install that in a test project. Could have been something weird on my machine though.

**Comment by airjp73** [comment]
Found some time to fix it. Part of the issue was also that I was including a private package that only exists in this monorepo in `dependencies` instead of `devDependencies`.

**Comment by airjp73** [comment]
Looks like it's working now in the latest patch.

**Comment by klipstein** [comment]
Thanks for the quick fix. I can confirm that it works now.
