### ISSUE TITLE
Zod validation does not show refine errors

### ISSUE THREAD

**Issue by engelkes-finstreet** [airjp73/remix-validated-form#21]
Hey, 
I started to play around with remix and enjoy using this library so far since I used Zod in my Blitz.js projects as well. Right now I have a problem that my refined validations are not shown as error.

My validator:
`const password = z
  .string()
  .min(6, "Das Passwort darf maximal 6 Zeichen lang sein")
  .max(100);

export const registerValidator = withZod(
  z
    .object({
      email: z.string().email(),
      password,
      passwordConfirmation: password,
    })
    .refine((data) => data.password === data.passwordConfirmation, {
      message: "Passwords don't match",
      path: ["passwordConfirmation"],
    })
);`

My Form:
`export const RegisterForm = () => (
  <ValidatedForm validator={registerValidator} method={"post"}>
    <Stack spacing="6">
      <TextField label={"E-Mail"} name={"email"} />
      <PasswordField label={"Passwort"} name={"password"} />
      <PasswordField
        label={"Passwort Bestätigen"}
        name={"passwordConfirmation"}
      />
      <Button type="submit" colorScheme="blue" size="lg" fontSize="md">
        Registrieren
      </Button>
    </Stack>
  </ValidatedForm>
);`

The normal validation for email / password and passwordConfirmation is working so far but the refined value never shows. Is there anything I am doing wrong or are these refined values not supported yet?

**Comment by airjp73** [comment]
Hi @engelkes-finstreet! Thanks for bringing this up.

This is probably just an oversight in the code for processing the errors.

I probably will have time later tonight or tomorrow. If you have time, it would be super helpful (but totally optional) if you made a PR with a failing test. It would go at the bottom of this file with the other zod-specific tests. https://github.com/airjp73/remix-validated-form/blob/main/packages/validation-tests/tests/validation.test.ts

**Comment by engelkes-finstreet** [comment]
Hey @airjp73,
thanks for the response. I will look a bit deeper into the code and try to fix / to add a failing test here!

**Comment by engelkes-finstreet** [comment]
Sorry if this a basic question. I checked out the repository and ran `yarn install`. 
Afterwards I get errors in both validator packages for the import of `remix-validated-form`: 

Cannot find module `remix-validated-form` or its corresponding type imports.

Is there anything else I have to execute to link the dependencies?

**Comment by airjp73** [comment]
The reason is probably that you haven't built anything yet. That should happen automatically if you run the tests, but if not you can run `yarn build` from the root.

Might be a good idea to add some of this info to a CONTRIBUTING.md file 😄

**Comment by engelkes-finstreet** [comment]
That resolved the error 👍 
I will updated the `CONTRIBUTING.md` with another pull request after I am done

**Comment by engelkes-finstreet** [comment]
@airjp73 Sorry, there was an error with my zod schema. Just figured it out and it is working now!

**Comment by BillBrower-Shopify** [comment]
This is still an issue in `5.1.0` with version `3.22.3` of Zod. Refine errors cause validation to fail but the errors themselves are not surfaced by `useField`.
