### ISSUE TITLE
[Bug]: Error using onSubmit with preventDefault()

### ISSUE THREAD

**Issue by piotrkulpinski** [airjp73/remix-validated-form#211]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [X] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

@remix/react: 1.7.5
remix-validated-form: 4.6.4

### Please provide a link to a minimal reproduction of the issue.

.

### Steps to Reproduce the Bug or Issue

```
import { ValidatedForm } from 'remix-validated-form';

...
const onSubmit = (data: any, e: FormEvent<HTMLFormElement>) => {
    console.log(data)

    e.preventDefault()
  }

...
return (
    <ValidatedForm
      ...
      onSubmit={onSubmit}
    >
      ...
    </ValidatedForm>
);
```

Error:
`Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'isSubmitting')`

### Expected behavior

Be able to use ValidatedForm without submitting it.

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [105]

### Additional context

```
createFormStore.ts:166 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'isSubmitting')
    at createFormStore.ts:166:13
    at createFormStore.ts:508:38
    at immer.esm.js:1:16024
    at e.produce (immer.esm.js:1:16172)
    at immer.esm.js:1:15978
    at n (vanilla.js:5:55)
    at n.setState (immer.js:6:12)
    at createFormStore.ts:508:23
    at endSubmit (createFormStore.ts:165:5)
    at $t (ValidatedForm.tsx:331:19)
```

Full error stack:
```
(anonymous) @ createFormStore.ts:166
(anonymous) @ createFormStore.ts:508
(anonymous) @ immer.esm.js:1
produce @ immer.esm.js:1
(anonymous) @ immer.esm.js:1
n @ vanilla.js:5
n.setState @ immer.js:6
(anonymous) @ createFormStore.ts:508
endSubmit @ createFormStore.ts:165
$t @ ValidatedForm.tsx:331
await in $t (async)
onSubmit @ ValidatedForm.tsx:359
React2.createElement._extends2.onSubmit @ components.js:728
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
```

**Comment by airjp73** [comment]
Hmm, this is a weird one. Does this form have an `id` prop? Might help with debugging.

Please provide a reproduction in a codesandbox if you can -- it saves a ton of debugging time.

**Comment by piotrkulpinski** [comment]
I tried to create a reproduction but the issue appears only in my specific case.
Still not sure what's happening, though. 

What could be the reason for `state` being undefined [here](https://github.com/airjp73/remix-validated-form/blob/main/packages/remix-validated-form/src/internal/state/createFormStore.ts#L166)?

**Comment by piotrkulpinski** [comment]
NVM, I found the issue. It was due to the unique `key` prop being set on the wrapper component which caused it to re-render.
