### ISSUE TITLE
[Feature]: focus first invalid field if server validation fails

### ISSUE THREAD

**Issue by tkovis** [airjp73/remix-validated-form#220]
### What is the new or updated feature that you are suggesting?

There is already a feature, that if you set client side validation to happen onSubmit and the validation fails, then focus gets set on the first invalid field. This doesn't seem to be the case if the client validation is ok, but server validation fails. I found a workaround that seems to work fine.

```tsx
import { useEffect, useRef } from "react";
import { useField, useFormContext } from "remix-validated-form";

type MyInputProps = {
  name: string;
  label: string;
};

export const TextInput = ({ name, label }: MyInputProps) => {
  const textInput = useRef<HTMLInputElement>(null);
  const { error, getInputProps } = useField(name);
  const { hasBeenSubmitted, fieldErrors, getValues } = useFormContext();
  useEffect(() => {
    if (error && hasBeenSubmitted && textInput.current) {
      const erroredFields = new Set(Object.keys(fieldErrors));
      const [firstErroredField] = Array.from(getValues().keys()).filter((k) =>
        erroredFields.has(k)
      );
      if (firstErroredField === name) {
        textInput.current.focus();
      }
    }
    // don't depend on fieldErrors to avoid unintented focus while editing
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [error, getValues, hasBeenSubmitted, name]);
  return (
    <div>
      <label htmlFor={name}>{label}</label>
      <input {...getInputProps({ id: name, type: "text", ref: textInput })} />
      {error && <span>{error}</span>}
    </div>
  );
};

```

### Why should this feature be included?

Moving focus to an invalid field after submit if there are server validation errors improves usability for keyboard users. This has already been implemented for client side validation errors on submit. Workaround exists, but implementing it is error prone and new users might not find it.

**Comment by airjp73** [comment]
Hi! This was added in #217, which I've just now deployed as v4.6.6.
