### ISSUE TITLE
[Feature]: Get zod schema from a validator instance

### ISSUE THREAD

**Issue by gabimor** [airjp73/remix-validated-form#221]
### What is the new or updated feature that you are suggesting?

most of the time i'm using something like
```
const myValidator = withZod(z.object(...))
```

i'd really with there was a `myValidator.getSchema()` (some time i need access to the schema but don't to keep around my schema in a separate var as this makes for some duplication of naming for every validator like: code

so instead of (LESS OPTIMAL)
``` 
const mySchema1 = z.object(...)
const myValidator1 = withZod(mySchema1)

const mySchema2 = z.object(...)
const myValidator2 = withZod(mySchema2)

const mySchema3 = z.object(...)
const myValidator3 = withZod(mySchema3)
```

``` 
const myValidator1 = withZod(z.object(...))

const myValidator2 = withZod(z.object(...))

const myValidator3 = withZod(z.object(...))


// and whenever I do need the schema:
myValidator3.getSchema()
```

### Why should this feature be included?

prevent code duplication

**Comment by airjp73** [comment]
Hi!

I'm not sure I understand the use-case here, could you tell me a bit more about that? Using the schema separately from the validator seems like it would be an uncommon enough pattern that adding support to the api isn't worth it. I don't really see this being code duplication either.

**Comment by gabimor** [comment]
hi, thanks for replying! actually since writing this i've found a better patten for implementing subactions with rvf:
```typescript
export enum Subactions {
  subaction1 = "subaction1",
  subaction2 = "subaction2",
}

const subaction1Schema = z.object({
  subaction: z.literal(Subactions.subaction1),
  param1: z.string().min(4), // for instance, parameters for the action go here
})

const subaction2Schema = z.object({
  subaction: z.literal(Subactions.subaction2),
  param1: zfd.numeric(z.number()), // for instance, parameters for the action go here
  param2: z.string().min(1), // for instance
})

const actionsValidator = withZod(
  z.discriminatedUnion("subaction", [subaction1Schema, subaction2Schema]),
)


// and then the action looks like this
export async function action({ request }: ActionArgs) {
  const validatedForm = await actionsValidator.validate(
    await request.formData(),
  )
  if (validatedForm.error) return validationError(validatedForm.error)

  const { data } = validatedForm

  if (data.subaction === Subactions.subaction1) {
  	// code here is has `data` correctly typed
  } else if (data.subaction === Subactions.subaction2) {
	// same here
  }
```

**Comment by gabimor** [comment]
maybe add this to the documentation ? I feel this is a common pattern many will run across, it took me some time to understand how to do this with no code duplication and boilerplate, and have type safety

**Comment by airjp73** [comment]
Yeah, this could be a useful pattern to document. I use it quite a lot, myself. 😊
