### ISSUE TITLE
[Bug]: Zustand deprecated the default export for `create`

### ISSUE THREAD

**Issue by justinwaite** [airjp73/remix-validated-form#231]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form`: 4.6.7
- `zustand`: 4.3.1

### Please provide a link to a minimal reproduction of the issue.

N/A

### Steps to Reproduce the Bug or Issue

1. Install latest version of zustand in your project
2. Open the console and notice the message `index.mjs:32 [DEPRECATED] default export is deprecated, instead import { create } from'zustand'`

### Expected behavior

The above warning should not be thrown

### Screenshots or Videos

![Screen Shot 2023-01-10 at 12 19 21 PM](https://user-images.githubusercontent.com/8517615/211641969-d65395c2-36b1-457d-9e7d-cbc01a2549b6.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Sorry I don't have time to create a repro example, but it should be a simple update.

Here's the release notes from Zustand on 4.3.0: https://github.com/pmndrs/zustand/releases/tag/v4.3.0

**Comment by JeffBeltran** [comment]
not sure if i overlooked things but how is this project released? mostly im curious if this just hasn't been released yet as im still seeing this.

Thanks
