### ISSUE TITLE
[Feature]: Dynamically update data inside array when user types in the field

### ISSUE THREAD

**Issue by kevin1193** [airjp73/remix-validated-form#235]
### What is the new or updated feature that you are suggesting?

Im using useFieldArray and it does not dynamically update the data inside it while use is typing. Can we have this feature? Or is there any way to make it happen on the current version?

### Why should this feature be included?

This will enable for easy handling of dynamic array values realtime

**Comment by kevin1193** [comment]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/4178188/215010880-195dec3d-9aed-4b39-8f88-2001155a9e08.png">

I would be happy to help on this.

**Comment by airjp73** [comment]
If you're looking to track & update values of the fields themselves, you'll want to take a look at [useControlField](https://www.remix-validated-form.io/reference/use-control-field).

**Comment by airjp73** [comment]
I don't think this is something we can implement at the field array level because we leave inputs uncontrolled by default. `useControlField` can be used to access the values in individual fields though.
