### ISSUE TITLE
[Bug]: Not supporting <ValidatedForm reloadDocument>

### ISSUE THREAD

**Issue by Mange** [airjp73/remix-validated-form#241]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

```
"@remix-validated-form/with-zod": "^2.0.5",
"remix-validated-form": "^4.6.7",
"zod-form-data": "^1.2.4"
```

### Please provide a link to a minimal reproduction of the issue.

https://github.com/Mange/remix-redirect-repro

### Steps to Reproduce the Bug or Issue

1. `npm install && npm run dev`
2. Go to http://localhost:3000
3. Test the different ways to submit.

### Expected behavior

Submitting a `<ValidatedForm reloadDocument>` should work the same was as a `<Form reloadDocument>`.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1599/215599929-9159a902-2bf4-45bd-8e6e-d1e6092262e6.png)

## All but the Form with reloadDocument

![image](https://user-images.githubusercontent.com/1599/215600045-a94fedcb-91d9-4886-921d-222908956298.png)

## Form with reloadDocument

![image](https://user-images.githubusercontent.com/1599/215600115-dfc32fea-22b3-409d-8b53-6474e7aa5cc9.png)

### Platform

- OS: Linux (Not relevant)
- Browser: Brave (Not relevant)
- Version: Not relevant

### Additional context

This breaks in `ValidatedForm` because it uses `useSubmit` under the hood, which does not respect `reloadDocument` or (AFACT) offers similar functionality.

I might not be diagnosing this issue correctly. It's all a guess from me.

I think a `reloadDocument` option should make it submit for a full page submit, like `noValidate` does, when JS is not available, but still submit the `<form>` for real without `useSubmit` if validations pass when JS is available.

Overall, I only want this behavior due to the lack of "hard redirects" in Remix, where I have some non-remix routes that I want to redirect to. If this is ever fixed upstream (remix-run/react-router#9859), then I won't care about this anymore.

**Comment by airjp73** [comment]
RVF v6 has been released 🎉 

`reloadDocument` should work as expected in v6. If there's an issue with it in v6, please feel free to open a new issue.

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).
