### ISSUE TITLE
[Feature]: Support for form level errors

### ISSUE THREAD

**Issue by tkovis** [airjp73/remix-validated-form#244]
### What is the new or updated feature that you are suggesting?

Some forms might have optional fields, but they require you to fill one of them. Eg.
```ts
const emailSchema = z.string().min(1).email("invalid email");
const phoneSchema = z.string().min(1).refine(isMobilePhone, "invalid phone");
const validator = withZod(
  z
    .object({
      email: emailSchema.or(z.literal("")),
      phone: phoneSchema.or(z.literal("")),
    })
    .refine(
      ({ email, phone }) =>
        emailSchema.safeParse(email) || phoneSchema.safeParse(phone),
      "set a valid phone or email."
    )
);
```
I looked through the docs and checked formContext, but it seems like there is only support for field level errors and not for errors that come from validating the form as a whole.

We personally decided to require email and make phone optional, but I thought this feature could be useful in the future for some rarer use cases. If you think this feature fits this project, I might return to implement it.

### Why should this feature be included?

Not all validation errors are specific to a field, but instead regard the form as a whole. With this it would be easy to validate the forms a whole and display an error message that advices the user on how to fix it.

**Comment by zhuhaow** [comment]
This feature would be very helpful and it may be implemented as a hook.

```tsx
function Error() {
  const error = useFormError();
  return {error ? <ShowError error={error} /> : null};
}
```

And the error can be parsed from server by `validationError`

```ts
if (error) {
return validationError(
      {
        fieldErrors: {
          username: "This username is already taken",
        },
        formError: {this_can_be_any_object: "or may be a list of strings?"}
        ...
      },
    );
}
```

**Comment by kenn** [comment]
I think this feature is very helpful.

In my case, `remix-validated-form` feels fragile and often breaks silently when changing the form structure.

For instance, when breaking up a complex object into multiple sections (appearance, advanced settings, etc.), it often stops responding on the client side, and there's zero visible feedback. I can only guess the error is happening on the other fields outside of the current sub-section of the form, but there's no way to see it.

The only clue I get is `useIsValid` which just returns `false` in that case, but it's not really helpful.

If we had the form-level global error structure, I'd be able to print where it went wrong, and fix the issue. (likely on the validator end, but it's hard to debug by guessing)

I think this is more of a developer-experience feature, but an important one if you have a large object with many fields that requires break down into multiple sections.

**Comment by airjp73** [comment]
RVF v6 has been released 🎉 

In v6 it should be possible to get form-level errors if you set your form-level error to some error key and render it using `form.error("myErrorKey")`. If there's still a problem in that version, please feel free to open a new issue.

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).
