### ISSUE TITLE
[Bug]: Controlled Inputs will not update when `defaultValues` are flattened key paths.

### ISSUE THREAD

**Issue by ZipBrandon** [airjp73/remix-validated-form#245]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

-  "remix-validated-form": "^4.6.8"

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/p/sandbox/quizzical-tess-8dgkon

### Steps to Reproduce the Bug or Issue

In the linked sandbox, I have three simplified examples of updating a controlled value. When the default values are instantiated from a plain object then the update succeeds.  In the the third case, when the default value is set with flattened keys it fails to update.

### Expected behavior

 In the the third case, when a default value is declared with a flattened key of a nested path (ex: `nested.name.first`) then the update does not succeed and reverts back to its default value.  I would expect this to work with the 4.6.7 and onward (https://github.com/airjp73/remix-validated-form/issues/204).

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by airjp73** [comment]
This is an interesting issue. It seems like we're ending up in a state where the object we store the values in looks like this:

```
{
  "name.first": "Default",
  "name.last": "Value",
  name: {
    first: "Foo",
    last: "Bar",
  },
}
```

And the default value is winning when selecting a value. Fixing this doesn't seem like an easy undertaking. I'll have to think on this a bit.

**Comment by airjp73** [comment]
RVF v6 has been released 🎉 

The guidance around how to structure default values has changed in v6 (I know you're already well into using v6 at this point haha). If it's still a problem in that version, please feel free to open a new issue.

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).
