### ISSUE TITLE
Number field validations withZod

### ISSUE THREAD

**Issue by zolrath** [airjp73/remix-validated-form#28]
When setting a validation using `withZod` it doesn't receive `<input type="number">` as numbers and zod doesn't seem to attempt to auto convert strings to numbers. At the moment I've been able to add a preprocess to the validation in order to convert to a number but it doesn't feel like it describes intent as cleanly.

```javascript
export const NumberTest = withZod(
	z.object({
		name: z.string().nonempty(),
		year: z
			.number()
			.gt(1500, "Year must be greater than 1500")
			.lt(2023, "Year must be less than 2023"),
		yearPreprocessed: z.preprocess(
			(val) => parseInt(val, 10),
			     z
				.number()
				.gt(1500, "Year must be greater than 1500")
				.lt(2023, "Year must be less than 2023"),
		),
	}),
);
```

![image](https://user-images.githubusercontent.com/454563/150006980-e162f2b9-5076-441e-b4c7-c6663359a7b1.png)

**Comment by airjp73** [comment]
Yeah, `zod` and `FormData` don't co-exist super intuitively. `zod` takes a very strict approach to type correctness whereas `yup` is meant for forms and will do this automatically. (don't get me wrong, I really like `zod`).

@fergusmeiklejohn and I went back and forth a lot about these interactions and I'm not totally sure what we can really do in this library to ease this pain point.

So far the best I can come up with is to export helpers from the `with-zod` package that would let you do something like this:

```ts
year: numberInput(
  z
    .number()
    .gt(1500, "Year must be greater than 1500")
    .lt(2023, "Year must be less than 2023")
)
```

but that's just a wrapper around a `z.preprocess`. We might do better to add an FAQ pointing people to `zod`'s `preprocess` documentation.

Open to hearing your ideas as well.

**Comment by airjp73** [comment]
Was poking around [remix-params-helper's](https://github.com/kiliman/remix-params-helper) code to see what that does. Looks like it actually inspects the schema and applies transformations based on the individual parts of the schema.

**Comment by zolrath** [comment]
Ahh that definitely feels smoother!

Could that be integrated into the `withZod` call or would there be a reason to not normalize the form data? Potentially a secondary argument to disable it as an escape hatch.

**Comment by airjp73** [comment]
I had some time to dig into this. Unfortunately, I don't think we can approach this by preprocessing the entire object. If we run into a schema like this, then we would have no way of correctly determining what to do with the field before validating.

```ts
const schema = z.object({
  numberOrString: z.union([z.string(), z.number()]),
})
```

That's a bit of a contrived example, but I definitely want to be able to use `union` with whatever solution we go with.

For now I'm going to start playing around with the first idea (preprocess helpers).

**Comment by airjp73** [comment]
Started playing around with some helpers after work and I like the direction it's going in. I'm planning on publishing them as a separate zod-form-data package when I get some time to finish it up.

**Comment by airjp73** [comment]
With the `zod-form-data` library, this schema could be written as:

```ts
export const NumberTest = withZod(
  z.object({
    name: zfd.text(),
    year: zfd.numeric(
      z.number()
        .gt(1500, "Year must be greater than 1500")
        .lt(2023, "Year must be less than 2023")
    ),
  })
);
```
