### ISSUE TITLE
[Bug]: `useIsSubmitting()` prevents data from being sent to the server

### ISSUE THREAD

**Issue by meoyawn** [airjp73/remix-validated-form#287]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- "remix-validated-form": "^4.6.11",
- "@remix-validated-form/with-zod": "^2.0.5",

### Please provide a link to a minimal reproduction of the issue.

https://github.com/meoyawn/remix-validated-form-use-is-submitting

### Steps to Reproduce the Bug or Issue

1. Enter a valid url in the input
2. Submit form
3. Observe text "Required" (observe empty FormData in the Chrome Network tab)

### Expected behavior

Submitting should render "Success". If you replace `useIsSubmitting()` call with `false`, you'll see it

### Screenshots or Videos

<img width="339" alt="image" src="https://github.com/airjp73/remix-validated-form/assets/1594148/fdb74c18-ac64-44a3-b04f-e41085979db5">

You can see that `formData` is not passed to the server:
<img width="785" alt="image" src="https://github.com/airjp73/remix-validated-form/assets/1594148/f6876c77-2740-4c49-8959-aa7b41e81122">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 113

### Additional context

`useIsSubmitting()` triggers React render, which replaces the form or something. Old `<input />` gets removed from the DOM, making `new FormData(form)` lose all the fields that get rerendered by `useIsSubmitting()`.

Sorry I couldn't get Remix to work with Codesandbox

**Comment by airjp73** [comment]
Hi!

This is happening because [you're disabling the input](https://github.com/meoyawn/remix-validated-form-use-is-submitting/blob/52cdc32252b3bdef0d9c378472159103e418db41/app/routes/_index.tsx#L67) when `isSubmitting === true`. A disabled input is never included in the `FormData`. To fix, you could use `readOnly` instead of `disabled`.

That said, this will likely be fixed when I implement a fix for #117.

**Comment by meoyawn** [comment]
Hey, no rush, I replaced `remix-validated-form` with `react-hook-form`

**Comment by meoyawn** [comment]
and thanks! TIL that Tailwind also has a `read-only:` variant https://tailwindcss.com/docs/hover-focus-and-other-states#read-only
