### ISSUE TITLE
[Feature]: Single input with value as array

### ISSUE THREAD

**Issue by cjoecker** [airjp73/remix-validated-form#295]
### What is the new or updated feature that you are suggesting?

For inputs like a multi-select, I would like to be able to be able to handle the value as a stringified array
<img width="318" alt="image" src="https://github.com/airjp73/remix-validated-form/assets/46030630/f05c9d08-e4bf-42f7-a160-3ebab30579e5">

I have for example a single input called `options`.
That input saves its value as `1,2,3` if I select the options 1,2,3
It would be nice if the library can understand that value as an array and not a string.

### Why should this feature be included?

I couldn't find in the documentation a good way to handle array values from a single input.
Creating hidden inputs for every single selected value is not that elegant in my opinion.

Here you have a code sandbox where you can reproduce what I mean:
https://codesandbox.io/p/sandbox/gifted-mirzakhani-799ysl

**Comment by jamalsoueidan** [comment]
I think this issue is related to MUI how they handle it, because in react-select it works out of the box when used with remix-validated-form, correct me if im wrong.

**Comment by cjoecker** [comment]
@airjp73 I like the idea of the helper. Having arrays as a string is something common. It can then be added to the arrays of documentation 👏

**Comment by airjp73** [comment]
RVF v6 has been released 🎉 

This use-case should be easily handled by [state mode](https://www.rvf-js.io/state-mode) in v6. If it's still a problem in that version, please feel free to open a new issue.

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).
