### ISSUE TITLE
[Bug]: @remix-validated-form/with-zod@2.0.5 peer dependency on remix-validated-form@5

### ISSUE THREAD

**Issue by stephen776** [airjp73/remix-validated-form#297]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

Same as previous bug: [#55](https://github.com/airjp73/remix-validated-form/issues/55)

### Please provide a link to a minimal reproduction of the issue.

https://github.com/airjp73/remix-validated-form/issues/55

### Steps to Reproduce the Bug or Issue

Install v5

### Expected behavior

Correct peer deps resolved.

### Platform

All

**Comment by airjp73** [comment]
I've also added unit tests for the peer dependency compatibility between the packages, so hopefully this won't happen again. ^.^
