### ISSUE TITLE
[Bug]: FieldArray 'replace' function sets field value as error message, causing false error display for inputs

### ISSUE THREAD

**Issue by andriialbatov** [airjp73/remix-validated-form#308]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [X] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

"@remix-validated-form/with-zod": "2.0.6",
"remix-validated-form": "5.0.2",

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/p/sandbox/billowing-lake-ff9gq9?file=%2Fapp%2Froutes%2Findex.tsx%3A84%2C10-84%2C20

### Steps to Reproduce the Bug or Issue

In the demo

1. Click on "Replace", which uses FieldArray 'replace' function and you will see errors in the input fields which was replaced

### Expected behavior

No error messages on inputs

### Platform

macos latest firefox and chrome

**Comment by airjp73** [comment]
Yep, looks like the logic for `replace` is incorrect. Will look into it.

**Comment by airjp73** [comment]
RVF v6 has been released 🎉 

This should no longer be a problem in v6. If it's still a problem in that version, please feel free to open a new issue.

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).
