### ISSUE TITLE
[Bug]: update zod results in an unexpected behaviour

### ISSUE THREAD

**Issue by maorun** [airjp73/remix-validated-form#320]
### Which packages are impacted?

- [ ] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [X] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form` : latest

### Please provide a link to a minimal reproduction of the issue.

https://github.com/maorun/remix-validated-form

### Steps to Reproduce the Bug or Issue

1. git clone https://github.com/maorun/remix-validated-form
2. run `npm run vitest` (looking normal)
3. run `yarn up zod`
4. run `npm run vitest` (missing second error)

### Expected behavior

As a user, I expected the update of zod has no changed in the error messages, but the last error is missed.

### Platform

- OS: macOS 13.4.1

### Additional context

```
z.array(
        z.number().positive(),
).parse(['asdf',  -232])
```
gives an correct error

**Comment by airjp73** [comment]
Looks like this might be an upstream issue in zod: https://github.com/colinhacks/zod/issues/2677

**Comment by maorun** [comment]
yeah that could be.
https://github.com/colinhacks/zod/pull/2719 should be fix that

**Comment by maorun** [comment]
seems to be fixed in https://github.com/colinhacks/zod/pull/2912
