### ISSUE TITLE
[Bug]: zod-form-data sets fields as optional, while the docs state otherwise, in the type that is

### ISSUE THREAD

**Issue by dietergeerts** [airjp73/remix-validated-form#323]
### Which packages are impacted?

- [ ] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [X] `zod-form-data`

### What version of these packages are you using?

- `zod-form-data`: `2.0.1`

### Please provide a link to a minimal reproduction of the issue.

Sorry, private repo

### Steps to Reproduce the Bug or Issue

The following:

```
import { zfd } from "zod-form-data";

const formSchema = zfd.formData({
  region_id: zfd.numeric(),
  header: zfd.text(),
});

function onSubmit({ target }: SubmitEvent) {
  updateSettings(
    formSchema.parse(new FormData(target as HTMLFormElement))
  );
}
```

Gives an error on the function, stating that the properties are required by the function, but are optional from the `parse` result, while the docs state that by default all things are required, so the type should also reflect this.

### Expected behavior

The type reflecting if a property is required or optional correctly according to the schema.

### Platform

- OS: [Windows 10]

**Comment by jvnlwn** [comment]
Possibly your tsconfig settings need adjusting.
- Checkout the Zod requirements: https://zod.dev/?id=requirements
- See related issue in Zod: https://github.com/colinhacks/zod/issues/2696

**Comment by dietergeerts** [comment]
> Possibly your tsconfig settings need adjusting.
> 
> * Checkout the Zod requirements: https://zod.dev/?id=requirements
> * See related issue in Zod: [Extract the inferred type is not working as expected colinhacks/zod#2696](https://github.com/colinhacks/zod/issues/2696)

Thx! That did the trick. Our project is just starting to use TS, and I wasn't aware yet of the full configuration for it :)

**Comment by airjp73** [comment]
Sounds like this is resolved. Is it okay to close the issue?
