### ISSUE TITLE
[Bug]:  peer dependency of zod@"^3.11.x" needs to be updated to 3.22.3 or greater

### ISSUE THREAD

**Issue by ceesss** [airjp73/remix-validated-form#329]
### Which packages are impacted?

- [ ] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `zod-form-data`: ^2.0.1

### Please provide a link to a minimal reproduction of the issue.

https://github.com/colinhacks/zod.git

### Steps to Reproduce the Bug or Issue

```
npm install zod@3.22.3
npm install zod-form-data
```

npm WARN Found: zod@3.22.2
npm WARN node_modules/zod
npm WARN   zod@"^3.22.3" from the root project
npm WARN   1 more (zod-form-data)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer zod@"^3.11.x" from zod-form-data@2.0.1
npm WARN node_modules/zod-form-data
npm WARN   zod-form-data@"^2.0.1" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for zod@^3.22.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Expected behavior

zod-form-data will use zod@3.22.3 or greater

zod advisory
https://github.com/advisories/GHSA-m95q-7qp3-xv42

### Platform

- OS: all

### Additional context

this should be a small update to support Zod 3.22

**Comment by airjp73** [comment]
Thanks for the heads up! I've been meaning to update the peer dep anyway.

**Comment by airjp73** [comment]
Should now be supported in zod-form-data 2.0.2 and with-zod 2.0.7. :)

Please feel free to reopen if the issue persists.
