### ISSUE TITLE
getInputProps for checkbox returns defaultValue when it should use defaultChecked

### ISSUE THREAD

**Issue by justinwaite** [airjp73/remix-validated-form#34]
Hey there, great package so far! This might be a lot to unpack, but I'll do my best to be clear.

Scenario: I am creating an "edit user" page where an admin can edit user details and change what permissions they have to the app. The create user flow worked flawlessly as far as I can tell, but in the edit flow I cannot get the checkbox list to properly hydrate those default states.

Here is the error that I'm getting from the browser:
```
Warning: ValidatedCheckbox contains an input of type checkbox with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://reactjs.org/link/controlled-components
```

I have the following schema:
```typescript
const schema = z.object({
  email: z.string().email(),
  passwords: z
    .object({
      password: z.string().min(6),
      passwordConfirmation: z.string(),
    })
    .refine((val) => val.password === val.passwordConfirmation, {
      path: ["passwordConfirmation"],
      message: "Passwords must match",
    }),
  firstName: z.string(),
  lastName: z.string(),
  isAdmin: zfd.checkbox().optional(),
  permissions: z
    .union([
      z.array(
        z.string().refine((val) => Object.values(UserPermission).includes(val as UserPermission), {
          path: ["permissions"],
          message: "Invalid permission",
        })
      ),
      z.string().refine((val) => Object.values(UserPermission).includes(val as UserPermission), {
        path: ["permissions"],
        message: "Invalid permission",
      }),
    ])
    .optional(),
});
```

and a form:
```tsx
<ValidatedForm
  method="post"
  validator={validator}
  defaultValues={defaultValues}
>
  <div>
    <ValidatedInput type="email" name="email" label="User email" readOnly disabled />
    <ValidatedInput type="text" name="firstName" label="First name" />
    <ValidatedInput type="text" name="lastName" label="Last name" />
    <ValidatedInput type="password" name="passwords.password" label="Password" />
    <ValidatedInput type="password" name="passwords.passwordConfirmation" label="Confirm password" />
  </div>

  <div>
    <ValidatedCheckbox
      className="sm:col-span-6"
      name="isAdmin"
      label="Admin user"
      value="on" // I had to add this because the library was adding a blank "value" prop otherwise, which broke it
      description="Admin users can update organization settings and manage users in addition to the following permissions"
      onChange={(checked) => setIsAdmin(checked)} // This is a bit of a hack to be able to disable the permissions list below
    />

    {permissions.map((permission) => (
      <ValidatedCheckbox
        key={permission.value}
        name="permissions"
        label={permission.label}
        value={permission.value}
        description={permission.description}
        id={`permission-${permission.value}`}
        disabled={isAdmin} // Is there a better way to get the current value of `isAdmin` other than tracking manually with useState?
      />
    ))}
  </div>

  <div>
    <SubmitButton submittingText="Saving...">Save</SubmitButton>
  </div>
</ValidatedForm>
```

and finally the ValidatedCheckbox component:

```tsx
const ValidatedCheckbox: React.FC<ValidatedCheckboxProps> = ({
  description,
  disabled,
  id,
  label,
  name,
  onChange,
  value,
}) => {
  const { error, getInputProps } = useField(name);

  const inputProps: any = getInputProps({
    id: id || name, // default to name if a specific id wasn't provided
    type: "checkbox",
    value, // this is for the user to optionally provide a custom value
    disabled,
  });

  // This function allows me to optionally track state changes of the checkbox in case I need to do other things
  // like show/hide/disable certain inputs based on the value of a checkbox
  const handleChange: ChangeEventHandler<HTMLInputElement> = (event) => {
    (inputProps as any).onChange(event.target.checked); // I noticed that the types recently screwed up and now I have to cast to `any`
    onChange?.(event.target.checked);
  };

  return (
    <div>
      <div>
        <input
          {...inputProps}
          onChange={handleChange}
        />
      </div>
      <div>
        <label htmlFor={inputProps.id}> {label} </label>
        <p id={`${inputProps.id}-description`}> {description} </p>
        {error ? (
          <p id={`${inputProps.id}-error`}> {error} </p>
        ) : null}
      </div>
    </div>
  );
};

export default ValidatedCheckbox;
```

It seems that `getInputProps` should be using `defaultChecked` instead of `defaultValue` for checkboxes. Maybe the fix is as simple as that?

Indeed, if I add this guard to the ValidatedCheckbox component, I can get the default values to work as expected:
```typescript
  if (inputProps.hasOwnProperty("defaultValue")) {
    if (Array.isArray(inputProps.defaultValue)) {
      inputProps.defaultChecked = inputProps.defaultValue.includes(value);
    } else if (typeof inputProps.defaultValue === "boolean") {
      inputProps.defaultChecked = inputProps.defaultValue;
    } else {
      inputProps.defaultChecked = inputProps.defaultValue === value;
    }
    delete inputProps.defaultValue;
  }
```

**Comment by airjp73** [comment]
Hi! I agree that this is a little unintuitive.

For checkboxes, I think it's generally going to be a good idea to skip `getInputProps` entirely. There's a section in the docs [here](https://www.remix-validated-form.io/repeated-field-names) (Writing a checkbox component) where I suggest that.

I'll have to think a bit on what a library-level solution would be for making this more intuitive. I suppose we could tweak the props we use if `type: 'checkbox'` is passed into `getInputProps`, but I'm not sure how to account for both the individual checkbox case and the checkbox group case if we do that.

On another note, I think you can probably make the permissions check in your schema a little nicer if you use `repeatableOfType`.

```ts
permissions: zfd.repeatableOfType(z.nativeEnum(UserPermission))
```

**Comment by AlonGvili** [comment]
I don't know if it related or not but the error comes from react and you going to get this error if you use like it says value and defaultValue, if you using value i think react is excepted to see onChange as well that signal to react its a control input

**Comment by justinwaite** [comment]
> I don't know if it related or not but the error comes from react and you going to get this error if you use like it says value and defaultValue, if you using value i think react is excepted to see onChange as well that signal to react its a control input

It works fine if you use `value` with `defaultChecked`, but not `value` with `defaultValue`. See my solution at the end of the post, that seems to work well.



> Hi! I agree that this is a little unintuitive.
> 
> For checkboxes, I think it's generally going to be a good idea to skip `getInputProps` entirely. There's a section in the docs [here](https://www.remix-validated-form.io/repeated-field-names) (Writing a checkbox component) where I suggest that.
> 
> I'll have to think a bit on what a library-level solution would be for making this more intuitive. I suppose we could tweak the props we use if `type: 'checkbox'` is passed into `getInputProps`, but I'm not sure how to account for both the individual checkbox case and the checkbox group case if we do that.
> 
> On another note, I think you can probably make the permissions check in your schema a little nicer if you use `repeatableOfType`.
> 
> ```ts
> permissions: zfd.repeatableOfType(z.nativeEnum(UserPermission))
> ```

Hey there! I must have missed that part of the docs where it says to build it myself, that would definitely make sense. I'll keep it the way I have it right now with this check:
```
  if (inputProps.hasOwnProperty("defaultValue")) {
    if (Array.isArray(inputProps.defaultValue)) {
      inputProps.defaultChecked = inputProps.defaultValue.includes(value);
    } else if (typeof inputProps.defaultValue === "boolean") {
      inputProps.defaultChecked = inputProps.defaultValue;
    } else {
      inputProps.defaultChecked = inputProps.defaultValue === value;
    }
    delete inputProps.defaultValue;
  }
```

This seems to handle the multiple and single values really well. There might be edge cases that I'm not considering here, but for me it's working out and gets rid of the error.

Thanks for that tip on using `nativeEnum`, definitely missed that when going over the zod docs.

**Comment by airjp73** [comment]
I think that code to transform the default value just about covers it.

I'll add some extra handling for this situation [similar to what `formik` does](https://github.com/jaredpalmer/formik/blob/master/packages/formik/src/Formik.tsx#L891-L931).
