### ISSUE TITLE
[Bug]: The FieldArrayHelpers returned from useFieldArray don't know about the type argument.

### ISSUE THREAD

**Issue by VirtuaBoza** [airjp73/remix-validated-form#341]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form@5.1.5`

### Please provide a link to a minimal reproduction of the issue.

This is not a behavior issue.

### Steps to Reproduce the Bug or Issue

The FieldArrayHelpers returned from useFieldArray don't know about the type argument.

### Expected behavior

This line: https://github.com/airjp73/remix-validated-form/blob/main/packages/remix-validated-form/src/internal/state/fieldArray.tsx#L168 should forward the type argument to `FieldArrayHelpers` unless I'm mistaken.

### Platform

N/A

**Comment by airjp73** [comment]
RVF v6 has been released 🎉 

This should no longer be the case in v6. If it's still a problem in that version, please feel free to open a new issue.

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).
