### ISSUE TITLE
`getInputProps` might be better solely as `getValidationHandlers`

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [airjp73/remix-validated-form#35]
So this is just a little thought I wanted to share.

In my opinion the naming `getInputProps` is a little confusing, as it's main role is to simply pass through the event handlers for validation.

Given the below code:

```
<ValidatedForm validator={loginValidator} method="post" >
	<FormInput
		label="Email address"
		name="email"
		type="email"
		autoComplete="email"
		required
	/>
	<FormInput
		label="Password"
		name="password"
		type="password"
		autoComplete="current-password"
		required
	/>
      <button type="submit">
	      Sign in
      </button>
</ValidatedForm>
```

As it stands without knowing, I would expect to see all the additional props; `type`,  `autoComplete`  etc, come through.

In reality it would return the 2 event handlers and defaultValue. 

With no ability to actually add any more props there's also no reason defaultValue should come through by default, as you have access to it seperately out of useField and can choose what to do with it there.

Let me know whether you agree :D

**Comment by airjp73** [comment]
Hi! Thanks for raising your concerns. 😄 

I must admit I'm a little confused by your example since you're not showing a usage of `getInputProps`. I think it would be helpful for me if you could show me what your code for `FormInput` looks like.

My hope behind the name `getInputProps` is to communicate that it's using the [prop getter pattern](https://kentcdodds.com/blog/how-to-give-rendering-control-to-users-with-prop-getters). The goal of this is to make it so you don't really have to know or care which props `getInputProps` is returning.

For example, If you do this

```tsx
<input
  {...getInputProps({
    type: 'email',
    autoComplete: 'email',
    required: true,
    onBlur: () => doSomething(),
  })
/>
```

Then it would output all of the props you passed in combined with the props `getInputProps` is providing.

Which is why I'm also a little confused by this point you made:

> As it stands without knowing, I would expect to see all the additional props; type, autoComplete etc, come through.

because that's exactly the goal / expectation of this pattern.

**Comment by TheRealFlyingCoder** [comment]
Oh Interesting! Unless i'm missing it, there's no explanation of that functionality / pattern / expectation in your docs? :(

I guess it's simple enough to retain type safety via this:

```
<input
  {...getInputProps<HTMLProps<HTMLInputElement>>({
    type: 'email',
    autoComplete: 'email',
    required: true,
    onBlur: () => doSomething(),
  })
/>
```

It's more a question of, why send every prop through to this function that only touches 2 event handlers.

I'm not sure if this method would work, but i'd rather the library do less work, and I get to keep native HTML like this:

```
const { defaultValue, validationHandler } = useField(name);

return (
  <input
    name={name}
    id={id}
    type="email"
    autoComplete="email"
    required
    onBlur={validationHandler}
    onChange={validationHandler}
  />
);
```

That way the user can just decide where and how to trigger validation, extend it however they please, and there's zero markup change.

Especially useful for existing projects that want to bring in the validation, and creates a lot more flexibility

**Comment by TheRealFlyingCoder** [comment]
Just realising the above suggestion is possible with `validate` already!

I wonder whether the Docs should show the setup without `getInputProps` first, so that the users understand what's going on before abstracting it away into a helper function?

**Comment by airjp73** [comment]
> Oh Interesting! Unless i'm missing it, there's no explanation of that functionality / pattern / expectation in your docs? :(

This could probably be made clearer. I do mention the term `prop-getter` in the API reference but don't really give a best practice on how to use it.

> I guess it's simple enough to retain type safety via this:

Type safety _should_ already "just work" if you're spreading the props into the input (is it broken?). I'll be publishing some changes this week that should clean up the type definition a little more, too.

> I'm not sure if this method would work, but i'd rather the library do less work, and I get to keep native HTML like this:

> I wonder whether the Docs should show the setup without getInputProps first, so that the users understand what's going on before abstracting it away into a helper function?

This was how things worked before I added `getInputProps`. Once I added support for tracking `touched` states it seemed like a lot of boilerplate to set up right off the bat. It's tricky to find the balance between "get up and running fast" and "here's everything that's going on".

**Comment by TheRealFlyingCoder** [comment]
Yeah okay so everything is fine in the package, and it's just clarity in the docs that's needed 😛

 >Type safety should already "just work" if you're spreading the props into the input (is it broken?). I'll be publishing some changes this week that should clean up the type definition a little more, too.

You are right, not sure why it wasn't popping up before 👀 

>This was how things worked before I added getInputProps. Once I added support for tracking touched states it seemed like a lot of boilerplate to set up right off the bat. It's tricky to find the balance between "get up and running fast" and "here's everything that's going on".

Yeah I think it's just offering the explanation and options to the dev so they know what's happening and can make an informed choice which path to take 👍

Anyways thanks for the quick replies! I hope this was informative / helpful in some capacity 😄
