### ISSUE TITLE
[Feature]: Support setFieldValue on useFormContext

### ISSUE THREAD

**Issue by cjoecker** [airjp73/remix-validated-form#354]
### What is the new or updated feature that you are suggesting?

I would like to have a `setFieldValue(fieldName:string)` in the `useFormContext` hook.

Right now, I only have `useControlField` to set a field value programmatically.

### Why should this feature be included?

I'm doing an API call on the client and want to set many field values programmatically. I don't see an option to replace many field values at once.

**Comment by airjp73** [comment]
This feature is present in v6 which is being released today. 🎉
