### ISSUE TITLE
[Feature]: Validate minimum length of text() type

### ISSUE THREAD

**Issue by danivideda** [airjp73/remix-validated-form#356]
### What is the new or updated feature that you are suggesting?

In the regular Zod, they have z.string().min({value}) to validate the minimum length of the string.
Can zod-form-data have this feature too?

Thank you

### Why should this feature be included?

To match the functionality of the regular Zod

**Comment by airjp73** [comment]
Hi!

To achieve this with zod-form-data, you can pass the schema into `zfd.text`.

```ts
zfd.text(
  z.string().min(5)
)
```

Or alternately, you can also still call `refine` like you would with any other schema.

```ts
zfd.text().refine(val => val.length > 5)
```
