### ISSUE TITLE
[Bug]: zod-form-data gives different results depending on the sort order of properties in the schema

### ISSUE THREAD

**Issue by thdk** [airjp73/remix-validated-form#359]
### Which packages are impacted?

- [ ] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [X] `zod-form-data`

### What version of these packages are you using?

zod-form-data: 2.0.2

### Please provide a link to a minimal reproduction of the issue.

https://stackblitz.com/edit/vitest-dev-vitest-bfrru6?file=test%2Fbasic.test.ts&view=editor

### Steps to Reproduce the Bug or Issue

```ts
import { describe, expect, test } from 'vitest';
import { z } from 'zod';
import { zfd } from 'zod-form-data';

describe('zfd', () => {
  test.each([
    {
      name: 'repeatable() before text()',
      // this schema works
      schema: zfd.formData({
        field1: zfd.repeatable(),
        field2: zfd.text(),
      }),
    },
    {
      name: 'text() before repeatable()',
      // this schema does not work
      schema: zfd.formData({
        field2: zfd.text(),
        field1: zfd.repeatable(),
      }),
    },
  ])(
    'validates form data when a schema is defined with $name',
    async ({ schema }) => {
      const data = new FormData();
      data.append('field1', '');
      data.append('field2', '');

      const result = await schema.safeParseAsync(data);

      expect(result.success).toBe(false);

      if (result.success) {
        throw new Error('Expected failure but got success');
      } else {
        const errors = result.error.flatten() as z.inferFlattenedErrors<
          typeof schema
        >;

        expect.soft(errors.fieldErrors.field1).toEqual(['Required']);
        expect.soft(errors.fieldErrors.field2).toEqual(['Required']);
      }
    }
  );
});

```

### Expected behavior

It shouldn't matter in which order the form fields are defined in the schema.

All validation issues should always be detected in one go. 

No matter if schema is defined as:
```ts
zfd.formData({
    field1: zfd.repeatable(),
    field2: zfd.text(),
})
```
or as:
```ts
zfd.formData({
    field2: zfd.text(),
    field1: zfd.repeatable(),
})
 ```

### Platform

- OS: MacOS
- Browser: arc

### Additional context

Could be related to my previous reported issue: https://github.com/airjp73/remix-validated-form/issues/358

**Comment by airjp73** [comment]
Hi again!

This one appears to be a zod bug: https://github.com/colinhacks/zod/issues/3123#issue-2074090247

Reproduction: https://stackblitz.com/edit/vitest-dev-vitest-w22qjv?file=test%2Fbasic.test.ts

**Comment by thdk** [comment]
Aha, thanks for pointing that out! This issue can be closed for me 👍🏼
