### ISSUE TITLE
[Feature]: How can I validate selection field?

### ISSUE THREAD

**Issue by zolzaya** [airjp73/remix-validated-form#48]
### What is the new or updated feature that you are suggesting?

Hey,

How can I validate selection field?

### Why should this feature be included?

Because I need a validate selection field.

**Comment by airjp73** [comment]
Hi!

The best place for questions like this would be Discussions rather than issues. 😊

Could you tell me more about your use case? Are you using an html select element, a custom component, something else?

**Comment by airjp73** [comment]
Hi again @zolzaya.

I'm going to close this issue but please feel free to ask your question in [Discussions](https://github.com/airjp73/remix-validated-form/discussions/new?category=q-a) with a little bit more information. 😄
