### ISSUE TITLE
HTML validation api doesn't play nicely with form-level validation

### ISSUE THREAD

**Issue by airjp73** [airjp73/remix-validated-form#5]
The native form validation api and the form-level validation don't play nicely together. If you hit "Submit" using a `ValidatedForm`, it should validate the entire form and show validation errors using you validation schema. But with the inputs marked as `required` in the html, the form-level validation never fires and only the native validation goes off.

I would love for these apis to compliment each other (remix-validated-form for better UX with JS, native api for validation without JS).

I think the fix is to disable html validation when JS is enabled. Could use `[useHydrated](https://github.com/sergiodxa/remix-utils#usehydrated) from `remix-utils` or make our own version to minimize dependencies.
```js
const isHydrated = useHydrated();
<form noValidate={isHydrated} />
```

**Comment by lucascurti** [comment]
Even when we disable JS we still get the validation from the server. If you ask me, I think it prefer to have this behaviour instead of relying on native validation when JS is disabled.

**Comment by airjp73** [comment]
That's a fair point. There's a lot of chatter in the remix discord about using the html validation API, but people using that might not be the target audience of this library.

Could add a prop to `enableNativeValidation` but set the form to `noValidate` by default.

**Comment by airjp73** [comment]
Eh, maybe the prop is unnecessary too. Let's just say `noValidate` and can address configuration when/if there's an issue about it.

**Comment by lucascurti** [comment]
Agree. I'm updating the README for #4. I'll drop a line about `noValidate`.

**Comment by airjp73** [comment]
I think the note in the README is enough for now, so I'm closing this,
