### ISSUE TITLE
[Bug]: @remix-validated-form/with-zod@2.0.0 peer dependency on remix-validated-form@3

### ISSUE THREAD

**Issue by canac** [airjp73/remix-validated-form#55]
### Which packages are impacted?

- [ ] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [X] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form`: ^4.0.2
- `@remix-validated-form/with-zod`: ^2.0.0

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/s/rough-lake-ver68

### Steps to Reproduce

Install the latest versions of `remix-validated-form` and `@remix-validated-form/with-zod` using npm.

```sh
npm install --save remix-validated-form@4.0.2 @remix-validated-form/with-zod@2.0.0
```

### Expected Behavior

The dependencies install correctly.

### Actual Behavior

There is a peer dependency error in npm because @remix-validated-form/with-zod@2.0.0 depends on remix-validated-form@"^3.x". Note that this is only a warning in yarn rather than a hard error like npm.

Error output:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: remix-app-template@undefined
npm ERR! Found: remix-validated-form@4.0.2
npm ERR! node_modules/remix-validated-form
npm ERR!   remix-validated-form@"4.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer remix-validated-form@"^3.x" from @remix-validated-form/with-zod@2.0.0
npm ERR! node_modules/@remix-validated-form/with-zod
npm ERR!   @remix-validated-form/with-zod@"2.0.0" from the root project
```

**Comment by airjp73** [comment]
Good call out. I didn't update those when I pushed out the 4.0 release. I'll fix later today.

**Comment by stephen776** [comment]
I am having this same issue again when updating go v5
