### ISSUE TITLE
[Bug]: Can't call an action outside the route the form is in if the form is in a dialog

### ISSUE THREAD

**Issue by fergusmeiklejohn** [airjp73/remix-validated-form#64]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- remix-validated-form v4.1.2
- @remix-validated-form/with-zod v2.0.1

### Please provide a link to a minimal reproduction of the issue.

https://github.com/fergusmeiklejohn/dialog-form-test

### Steps to Reproduce the Bug or Issue

Open localhost:3000
You'll see 3 buttons to open dialogs and one form
First dialog is HeadlessUI with a standard <Form />
Second dialog is HeadlessUI with a Remix Validated Form
Third dialog is ReachUI with a Remix Validated Form

The form at the bottom is a Remix Validated Form as a control outside a dialog.

Form in the first dialog works. The action in `api/test` just has a timeout so you can see it navigated to the URL, and the action console.logs out to the server.
Remix Validated Forms in dialogs 2 and 3 don't call the action in `api/test` and throw an error in the browser console

The control Remix Validated Form in the page works. 

### Expected behavior

I expected the Remix Validated Form to call the action in `api/test` when it is in a dialog

### Platform

macOS
Sizzy and Firefox

**Comment by airjp73** [comment]
Thanks for the detailed reproduction! There's definitely something funky going on here. I'll give it a look some time tonight.

**Comment by airjp73** [comment]
Fixed in v4.1.3

**Comment by fergusmeiklejohn** [comment]
Oh brilliant! yeah what a strange bug, I thought it must have something to do with Remix too but couldn't see how..

Thanks for fixing it so quickly :-)

**Comment by airjp73** [comment]
Whoops! Should be fixed now in v4.1.4.
