### ISSUE TITLE
[Bug]: Nested initial form values are updated on client side rendering

### ISSUE THREAD

**Issue by hauptrolle** [airjp73/remix-validated-form#75]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- "remix-validated-form": "^4.1.7",
- "zod-form-data": "^1.2.0"
- "@remix-validated-form/with-zod": "^2.0.1",

### Please provide a link to a minimal reproduction of the issue.

https://github.com/hauptrolle/remix-validated-form-nested-default-values-issue

### Steps to Reproduce the Bug or Issue

1. Clone the example
2. Reload the page
3. See that the defaultChecked state of the **nested** checkboxes are getting updated on client side rendering

### Expected behavior

The should not update.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 98.0

**Comment by airjp73** [comment]
Yeah, that's a bit weird. Thanks for the reproduction! I'll look into it later today.

**Comment by airjp73** [comment]
Should be fixed now in v4.1.8.
