### ISSUE TITLE
[Feature]: React 18 Support

### ISSUE THREAD

**Issue by nakleiderer** [airjp73/remix-validated-form#86]
### What is the new or updated feature that you are suggesting?

In the package.json, React is locked to `^17.0.2`, making it throw errors during install in a React 18 project. Could this library be released to allow React 18? As far as I can tell, this library would be fully compatible with no additional changes.

### Why should this feature be included?

Other than the general release of React 18, the Remix stacks have been updated to support React 18 out of the box, and this library is not possible to install in those projects. This adds significant friction, especially to folks new to Remix and could lead them to miss out on the value this library provides.

**Comment by nakleiderer** [comment]
I assume that we should use versions like this `^17.0.2 || ^18.0.0` to allow both v17 and v18 for a period of time.

**Comment by airjp73** [comment]
Published as v4.1.9
