### ISSUE TITLE
[Bug]: Custom select only re-validates after second change

### ISSUE THREAD

**Issue by dan-cooke** [airjp73/remix-validated-form#88]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

See codesandbox

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/s/long-forest-urul68?file=/app/routes/index.tsx

### Steps to Reproduce the Bug or Issue

1. Enter name, second name and email
2. Click submit
3. Observe the "Gender is required error"
4. Select "male" from the dropdown

### Expected behavior
The gender is required error should disappear

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by dan-cooke** [comment]
Apologies @airjp73  I can't believe it - but I was not entering a valid email. 

Buuut. I have just updated the Sandbox with another defect I am encountering.

I will update this ticket to reflect the new defect.

**Comment by dan-cooke** [comment]
https://user-images.githubusercontent.com/22816887/162209107-73c9c203-26a6-4abc-a0b8-13d2bff6ee29.mov

@airjp73  here is a screenshare of the current issue I am encountering.. 

Now I am using material-ui for the Select here.. so it could be an issue with that integration specifically

**Comment by airjp73** [comment]
This is an issue we still don't have a perfect solution for. What's happening is that the `validate` function synchronously validates the data in the form element. This works for native inputs but not for controlled components like this select (MUI is tracking the value in state internally). So we need to validate after the component rerenders with the new value. As a temporary workaround you could do something like this.

```ts
{...getInputProps({
  onChange: () => setTimeout(() => validate(), 0)
})}
```

I have an idea for a helper for controlled components specifically that I haven't had time to get in the library yet that could solve this.

It also might be possible to have `validate` be asynchronous all the time, but I'm not 100% sure we can make it reliable & concurrency-safe.

**Comment by dan-cooke** [comment]
I just stumbled across this solution myself. 

I'm currently just storing the components value and `validating` using a `useEffect`

Like so:

```tsx
  const [value, setValue] = useState();

  useEffect(() => {
    validate();
  }, [value]);

  const inputProps = getInputProps(selectProps);

  return (
    <Select
      {...inputProps}
      onChange={(e) => {
        setValue(e.target.value);
        inputProps?.onChange?.(e);
      }}
      error={!!error}
      helperText={error}
      autoComplete={name}
    >
      {children}
    </RnSelect>
```

Anyway - support for Controlled components would be awesome - maybe something similar to `Controller` from `react-hook-form` ?

Keep up the awesome work, really loving this lib

**Comment by airjp73** [comment]
> Anyway - support for Controlled components would be awesome - maybe something similar to Controller from react-hook-form

Yeah I'm thinking something along these lines. I have it implemented in a branch somewhere but haven't had time to see it all the way through and test & document it yet.
